CellProfiler/CellProfiler

cellprofiler/cellprofilerapp.py
cellprofiler/cpmath/otsu.py
cellprofiler/cpmath/zernike.py
cellprofiler/gui/cpframe.py
cellprofiler/gui/cpgrid.py
cellprofiler/gui/movieslider.py
cellprofiler/gui/preferencesdlg.py
cellprofiler/gui/regexp_editor.py

Hello! There are small changes for wxWidgets3.x compatibility and one bugfix for preferences dialog.
* Help window `cellprofiler.gui.htmldialog.HTMLDialog` available by click on *?* button in preferences dialog `cellprofiler.gui.preferencesdlg.PreferencesDlg` was inactive (impossible click *OK* or even just close window), because parent (`PreferencesDlg`) was modal.
* Now `PreferencesDlg` is nonmodal with separate `save_preferences` slot called by both *OK* and *Apply* buttons.
Tested with Archlinux x64, Windows 7 x64 (Anaconda + [gohlke](http://www.lfd.uci.edu/~gohlke/pythonlibs/) libs).

Update for wxWidgets 3.x 

---

README.md

It appears https://registry.hub.docker.com/u/cellprofiler/cellprofiler/ is the real repository, no longer the one belonging to `ljosa`. I've updated that in the README.

ljosa -> cellprofiler as the real docker repo

---

cellprofiler/icons/__init__.py
cellprofiler/tests/test_analysisworker.py
windows_setup.py

This isn't an ideal fix - it doesn't deal with a proper `pip install` and where the artwork goes in that case. But it restores CellProfiler to a working state.

fixes issue #1508. The icon was being loaded from the wrong place.

---

BatchProfiler/GetPipeline.py

GetPipeline was using an old initialization mechanism for fetching the batch and that's now updated. @dlogan, you can try the fixed version at http://imagewebrhel6/batchprofiler/cgi-bin/dev/ViewBatch.py?batch_id=15 and if that works, you can review the pull request, accept it and I'll update the official version (or you could leave it for @0x00B1 to check over) when I see that you've merged.

Fixes #1517 - BPBatch constructor's signature changed

---

cellprofiler/gui/pipelinecontroller.py

Hope you don't mind, Mark, I used "EnsureVisible" which won't scroll (and hide previous items) if it doesn't have to.

Fixes #1420 - use EnsureVisible to scroll the Choose Image Set/Group dialogs

---

cellprofiler/modules/filterobjects.py
cellprofiler/modules/tests/test_filterobjects.py

Use the small_objects_removed segmentation to preserve objects touching the border and still remove filtered objects

Fixed #1521 + test + cleanup of test_filterobjects

---

cellprofiler/modules/tests/test_measureobjectradialdistribution.py

@0x00B1 I forgot to put a pull request in for this one. My "mode" had a different signature than scipy.stats.mode and the original check-in broke some tests. This should fix it - can you check and merge to fix the build?

fixes #1548 scipy.stats.mode returns mode + # of elements at mode

---

cellprofiler/utilities/cpjvm.py
cpnose.py
java/pom.xml

@0x00B1 this gets rid of the SLF4J binding message and it uses the correct logger. In addition, I've added a more flexible way of specifying the location of the logging file "logback.xml". It looks in the following places (in this order):
./logback.xml
cellprofiler/utilities/logback.xml (relative to CellProfiler root dir)
java/src/main/resources/logback.xml
The error, `Warning:  org.apache.xerces.parsers.SAXParser: Property 'http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit' is not recognized.` is not handled by Java logging. See http://bugs.java.com/view_bug.do?bug_id=8016153

Fixes #1573 slf4j-simple excluded from POM

---

cellprofiler/modules/tests/test_trackobjects.py
cellprofiler/modules/trackobjects.py

A deprecated warning from numpy.delete points to a bug in the code. If the first track has a length of 1, then `idx` for label == 1 is zero and zero - 1 is -1 resulting in the warning message. The code should prevent that request for deletion.

issue #1571 don't delete lasts for label = 0 / fix for numpy.delete error

---

cellprofiler/modules/classifyobjects.py
cellprofiler/modules/measurecorrelation.py
cellprofiler/modules/tests/test_classifyobjects.py
cellprofiler/modules/tests/test_measurecorrelation.py

Protect against too few values in an object's measurements in ClassifyObjects
Tests for too few values and NaN for ClassifyObjects
Tests for NaN in MeasureCorrelation

Fixes #1553 MeasureCorrelation should output NaN for masked object

---

cellprofiler/modules/measureobjectneighbors.py
cellprofiler/modules/tests/test_measureobjectneighbors.py

Also prevents VisibleDeprecationWarning
Has test case that failed.

issue #1639 neighbors can get unfairly excluded if there are missing objects

---

cellprofiler/gui/cpfigure.py

I am guessing that Matplotlib is not using SetInitialSize to set the canvas size, so the code that set the size to 640x480 fails to work in wx 3.0. I used SetInitialSize after creating the canvas and it works now.

Fixes #1656 - set matplotlib canvas initial size to 640 x 480

---

.travis.yml
cellprofiler/modules/measureobjectneighbors.py
cellprofiler/modules/tests/test_measureobjectneighbors.py
cpnose.py

I introduced a bug in 9a2b6a6dc9981ddc0b5d566109067238d12fa78b that shows up when you calculate distances to the nearest neighbor. The distance matrix is computed excluding the objects touching the image border, but the neighbor_has_pixels array was calculated using objects touching the border as well (and these have larger object numbers than the ones that don't). The array size was wrong and the code failed as indicated.
@0x00B1 - this pull should get a little priority since the reporter is an ASTP client.

Fixes #1672 + tests. If objects are neighbors, distances don't include touching

---

cellprofiler/gui/moduleview.py
cellprofiler/gui/treecheckboxdialog.py

These fixes are needed to fix #1663 (behavior change in wx 3.0) and to expand the dialog box size so it fits the text under 3.0.

Fixes #1663 + some resizing to make the text fit

---

cellprofiler/modules/graytocolor.py
cellprofiler/modules/tests/test_graytocolor.py

This lets the user specify an arbitrary number of input images and colors for each. Each grayscale image is converted to its chosen color and then the set of color images are composited together by a simple addition.

Implement composite mode in GrayToColor

---

setup.py

Moved artwork from data to package_data.
Took me 3 hours to figure out how to write 5 lines of code. The big change is to build the imagej/jar directory in the build_lib directory which if you are doing `python setup.py install` is build\lib and if you are doing `pip install ...` is relative to a temp directory. I think what was happening is that the dependencies were previously being written to their target directories and ignored.
I also moved the artwork so that, for Windows, it installs to the lib/site-packages/artwork directory rather than the artwork directory. There is a slight problem in that "artwork" isn't technically a package because it's missing an __init__.py file. The script gives you a warning, but it does create the directory and package.
On Windows, the setup creates a …

Create imagej/jars dependencies in build_lib

---

cellprofiler/__main__.py

`if __name__ == "__main__"` is needed for expected `$ python -m cellprofiler` use

`python -m cellprofiler` fix

---

cellprofiler/gui/cpartists.py

Have to flip the numpy array instead of the matplotlib image and account for the fact that the translation then has to be done relative to the top and not the bottom of the window in this case.

Fixes #1746 - remove use of matplotlib flipud_out

---

cellprofiler/utilities/cpjvm.py

Solve the initial issue outlined in #1772 of allowing the override of JARs via the `CLASSPATH` environment variable.

Import CLASSPATH deps first (See #1772)

---

cellprofiler/modules/reassignobjectnumbers.py

Patched the checkout on the cluster, reran manually and it processed image set 7695 OK, now rerunning the failed job task.

Fixes #1789 On cluster, there was an overflow of an int8 segmentation.

---

cellprofiler/gui/pipelinecontroller.py

@dlogan - if you agree that it's worth not being able to select filenames as text from a Word document and drop them into the images module, please take this pull request if it passes the build.
Just hit the button.
Do it.

Fixes #1899 - remove drop file name text functionality

---

cellprofiler/gui/moduleview.py

To avoid repeated refresh, and to avoid auto-selection of text boxes.

moduleview: added missing self. to refresh_pending

---

cellprofiler/__main__.py

As mentioned on the forums [here](http://forum.cellprofiler.org/t/converting-example-pipeline-to-run-headless/3575/6?u=sjwarch), if `options.done_file` **is** `None`, then the exit code is never assigned.
Not sure why this is happening in our case, but it means the processes are not exiting on our cluster.

exit code never assigned

---

cellprofiler/modules/measureobjectintensitydistribution.py

#2193 highlighted a problem with calculating Zernikes even when not asked to.  It seems the check if Zernikes are wanted before calculating them does not check the value of the option but falls into Pythons default `True` if a class has no `__nonzero__` or `__len__` defined.
Reran some jobs which were failing and it now works when you have the Zernike option turned off.

Make sure we actually check the value of the option.

---

cellprofiler/module.py

Resolves #2380 
Not a great segmentation, but this gives an idea of the output:

Overlay labels on image in segmentation display

---

cellprofiler/__main__.py
cellprofiler/pipeline.py

The changes introduced in this PR make sure the Bio-Formats readers are closed when the app is terminated and after each pipeline cycle. This should prevent memory leaks and improve performance especially in conjunction with OMERO reader (java or python).

Close Bio-Formats readers

---

.travis.yml
cellprofiler/modules/measureobjectsizeshape.py
setup.py

Run `pip install -e . --process-dependency-links` to install scikit-image from source (verified os x).

Improve running time for MeasureObjectSizeShape (resolves #2548)

---

cellprofiler/module.py
cellprofiler/modules/activecontourmodel.py
cellprofiler/modules/measureobjectsizeshape.py
cellprofiler/modules/randomwalkeralgorithm.py
cellprofiler/modules/watershed.py
cellprofiler/utilities/hdf5_dict.py

Resolves #2553 
* `Image_Count` is an expected measurement when objects are present.
* MeasureObjectSizeShape does not measure the same features in 2D as in 3D. Defining separate measurements based on whether or not an image is 2D or 3D requires significant refactoring. Set unmeasured features to `NaN`.

Add missing measurements for Image, MeasureObjectSizeShape

---

.gitignore
cellprofiler/modules/gaussianfilter.py

Previously, the GaussianFilter module filtered uniformly across all dimensions. However, given the spatial differences that occur when acquiring z-stacks, i.e. the z-spacing is often greater than the pixel size, it is good practice to adjust the filter to account for this difference.

Anisotropic Gaussian filter

---

cellprofiler/modules/overlayoutlines.py

Also:
- Display input image title over input image
- Copy base image data before overlaying outlines so we can display original image (an in-place operation causes outlines to show up on original image).

Ensure base image values are in [0.0, 1.0]. (Resolves #2604)

---

cellprofiler/modules/enhanceorsuppressfeatures.py
tests/modules/test_enhanceorsuppressfeatures.py

Additionally, rescale intensity in [0, 1].
Before sigma scaling:
After sigma scaling:

Scale sigma by 1/spacing when enhancing neurites. 

---

cellprofiler/modules/filterobjects.py
tests/modules/test_filterobjects.py

* Don't use `globals()` in string formatting.
* Remove import aliases and optimize imports.
* PEP 08 compliance.

Fix formatting for FilterObjects

---

cellprofiler/modules/identifyprimaryobjects.py

Make "After declumping only" default for "Fill holes in identified
objects

Change default for "Fill holes in identified objects"

---

cellprofiler/__main__.py

`--get-batch-commands` did require a pipeline file and tried to run the pipeline after generating the batch commands. I don't see a use case for this behaviour.
Made some changes so that, if `--get-batch-commands` is present
- Cellprofiler will run headless, even if not explicitly asked for running headless by specifying `-c`
- No pipeline will be run
- No error message is thrown if `-p` is missing.

addressing some  commandline switch problems

---

CellProfiler.py

The easiest way for parallelization is to use multiprocessing Process. However it is not working on Windows when module is loaded by executable version of CellProfiler.
For example If we load module as plugin in CellProfiler 2.2 and try to use multiprocessing it tries to call CellProfiler.exe with --multiprocessing-fork which fails. 
It seems that the solution is very simple and safe, just call multiprocessing.freeze_support after == '__main__' check in CellProfiler.py to handle the additional parameter (see https://docs.python.org/2/library/multiprocessing.html)

Allow multiprocessing on Windows after freeze

---

cellprofiler/gui/moduleview.py
cellprofiler/setting.py

Additionally, validate the size is set and is a positive integer.
Resolves #2349

Don't raise exception when structuring element size is cleared.

---

cellprofiler/gui/moduleview.py
cellprofiler/modules/closing.py
cellprofiler/modules/dilation.py
cellprofiler/modules/erosion.py
cellprofiler/modules/opening.py
cellprofiler/setting.py

Resolves #2351 
Generate a validation warning when a structuring element of an incompatible dimensionality is selected. E.g., when a 3D structuring element is configured for a 2D pipeline:
...or a 2D structuring element is selected for a 3D pipeline and the module does not support planewise operations.

Warn when selecting an incompatible structuring element.

---

cellprofiler/module.py
cellprofiler/modules/images.py
cellprofiler/modules/measureobjectsizeshape.py
cellprofiler/modules/overlayoutlines.py
cellprofiler/setting.py
setup.py

Resolves #2860 (modules only)
Included is an example of how to format the module settings. Note that the documentation strings are not indented.
I will add support for the remaining help GUI elements in #2840

Render module help in GUI

---

cellprofiler/gui/figure.py
cellprofiler/gui/pipelinecontroller.py

Resolves #2965 
Fixes a bug in displaying an image from an image list. We needed to use the matplotlib 2.0.2 API.
Additionally, display NPY data and volumetric data (works only when the pipeline is configured for 3D in NamesAndTypes, otherwise displays as a 2D multichannel image).

Fix image display on double-click.

---

cellprofiler/gui/html/content.py
cellprofiler/gui/html/htmlwindow.py

Resolves #2943
Loads a version of the ExampleFly pipeline corresponding to the running
version of CellProfiler. If no matching pipeline is found, the pipeline
is run from master.
Assumes CellProfiler/examples is tagged with the a CellProfiler version
string. When releasing a new version of CellProfiler, remember to update
and tag CellProfiler/examples with the new version.

Load versioned example pipeline.

---

cellprofiler/modules/calculatestatistics.py

Please help at this part:
`
%(IO_WITH_METADATA_HELP_TEXT)s %(USING_METADATA_TAGS_REF)s For
instance, if you have a metadata tag named “Plate”, you can create a
per-plate folder by selecting one of the subfolder options and then
specifying the subfolder name as “\\g<Plate>”. The module will
substitute the metadata values for the current image set for any
metadata tags in the folder name. `%(USING_METADATA_HELP_REF)s.
`

Edit documentation CalculateStatistics

---

cellprofiler/modules/threshold.py

Note that the Adaptive thresholding method’s help described a ton of options but we only allow Otsu when Adaptive is chosen, so much of that text (redundant w the Global setting’s help) was removed.

Documentation - Threshold.py

---

cellprofiler/object.py

There was an error that was created with modules that displayed label images, like this...
```
File "cellprofiler\gui\pipelinecontroller.py", line 2890, in do_step
module.display(workspace, fig)
File "cellprofiler\module.py", line 1076, in display
y=0
File "cellprofiler\gui\figure.py", line 180, in wrapper
return fn(*args, **kwargs)
File "cellprofiler\gui\figure.py", line 1518, in subplot_imshow_labels
pixel_data=background_image
File "cellprofiler\object.py", line 973, in overlay_labels
colors=colors[unique_labels - 1],
IndexError: index 153 is out of bounds for axis 0 with size 153
```
@mcquin fixed #3049

@mcquin FTW. CP :goat:

---

cellprofiler/modules/editobjectsmanually.py
cellprofiler/modules/expandorshrinkobjects.py
cellprofiler/modules/filterobjects.py
cellprofiler/modules/identifyobjectsmanually.py
cellprofiler/modules/identifysecondaryobjects.py
cellprofiler/modules/identifytertiaryobjects.py
cellprofiler/modules/maskobjects.py
cellprofiler/modules/splitormergeobjects.py
tests/modules/test_editobjectsmanually.py
tests/modules/test_expandorshrinkobjects.py
tests/modules/test_identifysecondaryobjects.py
tests/modules/test_identifytertiaryobjects.py
tests/modules/test_maskobjects.py
tests/modules/test_splitormergeobjects.py

Resolves #3035 
Users should use **OverlayOutlines** and **SaveImages** to create and save outline images.

Don't save object outlines in object processing modules

---

cellprofiler/gui/pipelinelistview.py

Resolves #3062 
@DuaaAli and I figured out how to improve Test Mode visualization. The "running module" is the module that will run the next time "Step" is pressed. That module receives a blue/gray rectangle around it. You can select another module and it's highlighted in blue/gray (like normal), and the running module still gets a blue/gray box around it.
In this picture, we're in test mode. The running module is "IdentifyPrimaryObjects", but the module we're looking at is "Crop".
We've verified this functionality on Windows.

Focus on running module in test mode.

---

cellprofiler/modules/_help.py
cellprofiler/modules/identifyobjectsingrid.py
cellprofiler/modules/identifyobjectsmanually.py
cellprofiler/modules/identifytertiaryobjects.py
cellprofiler/modules/maskobjects.py
cellprofiler/modules/namesandtypes.py
cellprofiler/modules/overlayoutlines.py
cellprofiler/modules/splitormergeobjects.py
cellprofiler/modules/untangleworms.py
tests/modules/test_identifyobjectsingrid.py
tests/modules/test_namesandtypes.py

Resolves #3035 
Object identification modules no longer produce object outlines. Use **OverlayOutlines** to produce outline images.

Don't retain object outlines.

---

cellprofiler/modules/colortogray.py

Many changes are because it was likely originally written only for RGB and now handles other types.
I need two bits of help: 
1) pls check it's correct what I've changed from splitting -> combining
2) there are three similar settings like this: 
Select *"%(YES)s"* to extract the red channel to grayscale."""
My Q is: else what? Is it correct to add "Otherwise, the red channel will be (ignored?) (separated but stored as a color image?)" (if you know the answer please do make the change for red, green, and blue.

Documentation - ColorToGray

---

cellprofiler/modules/identifysecondaryobjects.py

I'd like to add a tech note icon at line 230. Someone else can just do this for me, or I can try it once the present changes are merged since it's dangerous w me not being able to check the GUI. 
Add at line 230:
- .. image:: {TECH_NOTE_ICON}
probably add the tech note line out of the below to line ~286:
""".format(**{
"PROTIP_RECOMEND_ICON": _help.PROTIP_RECOMEND_ICON,
"PROTIP_AVOID_ICON": _help.PROTIP_AVOID_ICON,
"TECH_NOTE_ICON": _help.TECH_NOTE_ICON
})

Documentation - IdentifySecondaryObjects

---

cellprofiler/gui/help/content.py

Running multiple pipelines only works with pipeline (.cppipe) files with image plane details. Use File > Export > Pipeline... to export "CellProfiler pipeline and file list".

Update run multiple pipelines documentation

---

cellprofiler/modules/expandorshrinkobjects.py

Update instructions for saving objects/outlines/object overlays. Additionally, add a documentation string to the setting "Number of pixels by which to expand or shrink".

Clarify documentation for ExpandOrShrinkObjects

---

cellprofiler/module.py
cellprofiler/modules/mergeoutputfiles.py

* Don't display "Settings:" when a module has none
* Render reST help as HTML in data tool viewer

Documentation formatting for MergeOutputFiles

---

cellprofiler/modules/loaddata.py

I need help in three places:
1) See the change related to “performing this task” - If I’m wrong about what that means, please adjust the language! 
2) For this setting, can someone adjust the language to make it clear whether the numbers should be separated by a comma or dash or something? 
Enter the row numbers of the first and last row to be processed
3) Please verify accuracy in this paragraph at line 10  (I removed something about loading old pipelines/superseding - please be sure that was not crucial info!)
This module loads a file that supplies text or numerical data associated
with the images to be processed, e.g., sample names, plate names, well
identifiers, or even a list of image file names to be processed in the
analysis run. Please note that most researchers will prefer to use …

Documentation - LoadData

---

cellprofiler/modules/threshold.py

which -> that
But also ensuring it sounds right in modules other than IdPrimary. The three-class description sounded pretty IdPrimary-centric when read in the context of other modules like IdSecondary.

Documentation - Threshold

---

cellprofiler/modules/exporttospreadsheet.py
tests/modules/test_exporttospreadsheet.py

Resolves #3161 
Added a bit to the documentation explaining that you may want to select columns when you are going to view the spreadsheet in a program which limit the number of rows and columns.
@bethac07 / @AnneCarpenter could you please check off on that documentation addition?

Remove option to limit exported columns.

---

cellprofiler/modules/saveimages.py

Resolves #3150 
The only supported file format for movies is TIFF. Remove the option to chose a file format when a movie is being saved.

Hide file format setting on saving movies

---

cellprofiler/modules/identifyprimaryobjects.py
cellprofiler/modules/identifysecondaryobjects.py
tests/modules/test_identifyprimaryobjects.py
tests/modules/test_identifysecondaryobjects.py
tests/test_knime_bridge.py

Resolves #2814 
Verified on pipeline submitted with issue. Also verified functionality with other modules such as FilterObjects.
Correct measurement objects:
* https://github.com/CellProfiler/CellProfiler/blob/1cf1a96e5613294149fff94dc7adb897bddfb594/cellprofiler/modules/identifyprimaryobjects.py#L1426-L1432
* https://github.com/CellProfiler/CellProfiler/blob/1cf1a96e5613294149fff94dc7adb897bddfb594/cellprofiler/modules/identifysecondaryobjects.py#L908-L912

Return correct measurement objects for IDPrimary and IDSecondary

---

cellprofiler/modules/imagemath.py

I found the sentence "Usually, the smallest mask of all image operands is applied after image
math has been completed. " to be confusing in its context. If someone who understands it can adjust the text, that'd be great.

Documentation - ImageMath

---

cellprofiler/modules/correctilluminationcalculate.py

1) The smoothing method setting said "See the **EnhanceOrSuppressFeatures** module help for more details. " That doesn't make sense to me, I assume it must've meant **Smooth**? Separately, I've made an issue to merge the settings documentation for smooth-related options within CorrecIllumCalc (#3194).
2) Can someone update the docs on Splines and Convex Hull... are they recommended, are they slow? Right now they are just described by pros/cons are not explained.
3) Note line ~321 I changed to FI_OBJECT_SIZE because I think it was wrong before, someone please confirm. Here is the context in case line numbers change: 
self.object_width = cps.Integer(
"Approximate object size", 10, doc="""\
*(Used only if %(FI_OBJECT_SIZE)s is selected for smoothing filter size calculation)*
Enter the …

Documentation - CorrectIlluminationCalculate

---

cellprofiler/modules/invertforprinting.py

I was too fast on the merge for #3134. Fixes setting text strings by escaping quotes.

Escape quotes around setting text.

---

cellprofiler/gui/figure.py
cellprofiler/modules/relateobjects.py
cellprofiler/object.py
tests/test_objects.py

Resolves #3268 
Add options to `subplot_imshow_labels` to generate up to a `max_label` number of colors, and shuffle them according to `seed`.

Display segmentations with missing/skipped labels.

---

cellprofiler/gui/preferencesview.py

Partial fix for #3235: 
Fixes the rendering of the help documentation in the GUI. Does not resolve the missing help on button press in builds.

Display help text as HTML in preferences view.

---

cellprofiler/modules/resize.py

Not life-threatening, but the setting "Method to specify the dimensions" and "Select the image with the desired dimensions" (currently the final two sections) should appear after "Resizing factor" (the 4th setting) in the help if possible.

Documentation - Resize

---

cellprofiler/modules/tile.py

FYI, I removed these lines (in the section on how to handle memory problems) which were pretty bizarre. I *think* it made sense if you replace "this module" with "SpeedUpCellProfiler", a module that cleared images from CP's memory. But I've no idea why someone would have replaced that module's name with "this module", and anyhow SpeedUpCellProfiler is no more. 
"-  Place this module prior to the **Tile** module (and maybe also
afterwards) and set it to retain only those images that are needed
for downstream modules."
I dunno why there is a vertical bar at line 46 so I left it.

Documentation - Tile

---

cellprofiler/modules/resizeobjects.py

#3123 
This is beyond the scope of this pull-request, but an option to preserve the Z-dimension, or not, would be a useful addition to make this module more general. The documentation for this module has been expanded to make it clear that the z-dimension is not resized, but the name of the module does not hint at this specific behavior. The same option would be useful in **Resize**.

elaborate on difference between ResizeObjects and ExpandOrShrinkObjects

---

setup.py

Resolves #3355
Resolves #3356
Matplotlib 2.1.0 contains at least two bugs which cause CellProfiler tests to fail. These bugs have been fixed in Matplotlib (see comments in resolved issues) and should be released in a later version. In the meantime, require versions 2.0.0+ but exclude 2.1.0.

Install matplotlib 2+, excluding 2.1.0

---

cellprofiler/gui/help/menu.py
requirements.txt

Resolves #3296 
I've published the [CellProfiler manual on RTD](http://cellprofiler.readthedocs.io/en/latest/) and enabled a webhook to automatically build the latest documentation whenever there's a change to CellProfiler (we can configure this, if this seems too aggressive). 
This PR re-enables the GUI's Help > Online Manual. It's configured such that is tries to access a version of the documentation matching the running CellProfiler version (e.g., "v3.0.0"). If that fails, it defaults to "latest". I handle the logic here since it doesn't seem configurable in RTD.
There's only one manual step (which I'd love to figure out whether or not it can be automated). When a new version is tagged/released, RTD will update "latest" but it won't automatically make the tagged version available …

Restore help manual GUI link.

---

setup.py

I've explicitly added the `data` directory to `setup.py` to allow it to be installed as a binary package, rather than just in editable mode. I also removed an unused package_data group that referenced the package `images` which did not exist. 
#3375

Add /data as additional package data for pip installs

---

cellprofiler/modules/measureobjectsizeshape.py
tests/modules/test_measureobjectsizeshape.py

Resolves #3352
AreaShape_Center_X and AreaShape_Center_Y were incorrectly flipped for
three-dimensional images.

Record AreaShape_Center measurements with correct X, Y.

---

cellprofiler/data/help/why_use_cellprofiler.rst
cellprofiler/gui/help/search.py
cellprofiler/modules/measureobjectintensitydistribution.py

Addresses #3407. Fixing this issue actually exposed a number of other issues, namely:
- `previous.png` (previous match arrow) wasn't displaying properly
- There was extra whitespace between the previous text arrow and the match term
- The first match title was duplicated
- No indication of count was actually displayed (it was only present in the title)

Fix help search 

---

cellprofiler/modules/fillobjects.py
tests/modules/test_fillobjects.py

This change is just to make FillObjects consistent with other modules in refering to planewise operations.

Slicewise->planewise in FillObjects for consistentcy with other modules

---

cellprofiler/gui/pipelinecontroller.py

Ensure viewer opens correct image path, see #3388

Fix opening images with spaces in filename

---

cellprofiler/modules/loadimages.py
tests/modules/test_loadimages.py

Resolves #3394
`skimage.io.imread` swaps axes on data it assumes to be multichannel.
CellProfiler only supports single-channel TIF stacks to represent
three-dimensional data. Avoid confusing stacks with only 3 or 4
planes with multichannel data by using `skimage.external.tifffile` to
load three-dimensional data.

Read TIF stacks with skimage.external.tifffile

---

cellprofiler/modules/identifyprimaryobjects.py
cellprofiler/modules/identifysecondaryobjects.py

Resolves #3338 
IDPrimary and IDSecondary were falsely reporting volumetric support. Overriding the volumetric method from the parent class to return `False` (rather than `True`) resolves the issue:
- Users cannot add non-3D modules to a 3D pipeline (dialog appears, prevents addition to pipeline)
- Users cannot run non-3D modules in a 3D pipeline (error is raised on run)

Indicate IDPrimary, IDSecondary do not support volumes.

---

cellprofiler/modules/exporttodatabase.py

In a highly concurent batch processing environment there can easily be
100s of instances of CellProfiler.  With a decently complicated
pipeline and images collected with large frame (2K x 2K+) cameras there
can also easily be several 100 objects per image.  Under these
conditions MySQL lock timeouts will occur when using the InnoDB database
engine which is the default as of MySQL 5.7.
The coarse grained lock was instituted in 26c3841 as a fix for #1022.
While that issue does not detail the specifics it can be assumed that
the deadlocks mentioned were related to gap locking:
https://dev.mysql.com/doc/refman/5.7/en/innodb-locking.html#innodb-gap-locks
The propensity for InnoDB to be affected by deadlocking problems is well
known.  So much so that there is a page dedicated to it in the MySQL …

Use `READ COMMITTED` isolation in place of coarse grained lock

---

.travis.yml
setup.py

This is a follow up to #3455 which fixes a runtime dependency resolution issue that manifests itself when having the `decorator` dependency explicitly set (2910fe126d75f00f0de14b2377807ae211093678) and following the [Ubuntu 16.04](https://github.com/CellProfiler/CellProfiler/wiki/Source-installation-%28Ubuntu-16.04-LTS%29) install documentation.
Everything will install fine, but you will get this exception when trying to run CellProfiler:
```
Traceback (most recent call last):
File "/home/callan/v/cp22-new/bin/cellprofiler", line 6, in <module>
from pkg_resources import load_entry_point
File "/home/callan/v/cp22-new/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2927, in <module>
@_call_aside
File "/home/callan/v/cp22-new/local/lib/python2.7/site-packages/pkg_resources/ …
```

Ubuntu 16.04 compatibility fix follow up

---

cellprofiler/gui/figure.py
cellprofiler/gui/preferencesdlg.py
cellprofiler/preferences.py

Resolves #3396.
Adds gamma adjustment/power law transformation. This feature can
be enabled via the figure menu or in the preferences dialog.
Additionally, allows configuring the value of gamma and the scale
of the log transformation in the preferences dialog, or when
the normalization option is selected from the figure menu.
Examples:

Improve visualization for low-contrast images.

---

cellprofiler/data/help/why_use_cellprofiler.rst
cellprofiler/modules/calculatestatistics.py
cellprofiler/modules/identifydeadworms.py
cellprofiler/modules/identifyprimaryobjects.py
cellprofiler/modules/makeprojection.py
cellprofiler/modules/measureimageoverlap.py
cellprofiler/modules/measureimagequality.py
cellprofiler/modules/measureobjectoverlap.py
cellprofiler/modules/measuretexture.py
cellprofiler/modules/straightenworms.py
cellprofiler/modules/threshold.py
cellprofiler/modules/trackobjects.py
cellprofiler/modules/untangleworms.py
docs/source/index.rst

See #3478 :-)   I used Atom's project-wide search-and-replace, so I guess I caught all them DOIs.

link DOIs to new, secure resolver

---

cellprofiler/data/help/why_use_cellprofiler.rst

Hello! I think that PR was a bit too quickly merged, because [I wanted revert an intermediate work-around](https://github.com/CellProfiler/CellProfiler/pull/3479#discussion_r166345745). So, this can revert 94f215df because patch d83bd941 was included in the mean-time. Cheers :-)

Follow-up to #3478

---

CITATION

Hello!
As discussed in [#3480](https://github.com/CellProfiler/CellProfiler/issues/3480). I think I got all the BibTeX snippets of the papers on [cellprofiler.org/citations](http://cellprofiler.org/citations/). Where the publisher didn't offer BibTeX, I imported them to [Zotero](http://zotero.org/) & exported with [Better BibTeX](https://retorque.re/zotero-better-bibtex/).
Cheers :-)

enable citation import from source code

---

cellprofiler/gui/namesubscriber.py

Resolves #3461 
These IDs were not used but were being created every time the module was displayed.
They were not being cleaned up, and so caused an overflow error when allocated new IDs.

Remove unused, yet created, wxIDs.

---

cellprofiler/modules/measureimageareaoccupied.py
cellprofiler/modules/measureimagequality.py
cellprofiler/modules/measureobjectsizeshape.py
tests/modules/test_measureimageareaoccupied.py
tests/modules/test_measureimagequality.py
tests/modules/test_measureobjectsizeshape.py

Resolves #3489 
E.g., use "Volume" and "SurfaceArea" instead of "Area" and "Perimeter". This is a breaking change that should be documented in the 3.1.0 release.

Use 3D feature names for 3D image/object measurements

---

cellprofiler/modules/convertimagetoobjects.py
tests/modules/test_convertimagetoobjects.py

If the objects from a pipeline were saved, there was no way to easily import them into a different pipeline as objects. This extends `ConvertImageToObjects` to (logically) convert an integer labeled array into objects. This conversion respects previous labels - it doesn't force to connected but separately labeled objects into a single, shared label.

Allow pre-labeled images to be used in ConvertImageToObjects

---

cellprofiler/modules/saveimages.py
tests/modules/test_saveimages.py

Previously, images were being stacked as YXC for images with greater than 5 channels. Most image handlers can handle `(M, N, 3)` or `(M, N, 4)` arrays, but beyond that they assume CYX ordering. For non-volumetric images with the 3rd dimension greater than 5, this flips the ordering when saving so it gets saved appropriately.
Also with added unit tests :nerd_face: 
Resolves #3509

Make image saving work with 5+ channels

---

cellprofiler/preferences.py

This resolves #3534, which was caused by some changes I made in #3515 (specifically https://github.com/CellProfiler/CellProfiler/commit/675f9dce75cc0bd8a12230a5062e979968b329b9#diff-7cb18eb352b9ed692a5450ab3e8a69ae)
Unfortunately, we can't write unit tests for this because we can't test wx on Ubuntu :upside_down_face: at least not as far as I'm aware.

Re-add config write types (this time with more documentation)

---

cellprofiler/modules/saveimages.py

Special thanks to @derekthirstrup for mentioning this - currently CellProfiler doesn't compress volumetric images when it saves them as tiffs, which means that an image that might be less than 1MB ends up taking 75MB or so. Based on some work that @karhohs did, I think it's reasonable for us to move over to compressing tiffs by default on the reg.

Compress volumetric tiffs by default

---

cellprofiler/modules/savecroppedobjects.py
tests/modules/test_savecroppedobjects.py

Re: #3544 It seems like saving masks as 8-bit PNG instead of 8-bit TIFF reduces the space required a satisfactory amount; it is a one-line fix. FWIW, I did not see a way to save a binary image with skimage, but did find an issue that alludes to this https://github.com/scikit-image/scikit-image/issues/1623.
I've been converting the TIFF images into PNG images after CellProfiler creates the crops/masks, so this would also save a step from a practical perspective.

PNG compression solves the storage issue

---

cellprofiler/modules/filterobjects.py
cellprofiler/modules/measureimageareaoccupied.py
cellprofiler/modules/measureobjectsizeshape.py
setup.py

* Update setup.py
* Change from marching_cubes to marching_cubes_classic
* marching_cubes to marching_cubes_classic
* marching_cubes_classic only returns verts and faces
* marching_cubes_classic only returns verts and faces
* Use scipy binary_erosion (as elsewhere)

skimage 0.14 fixes (#3580)

---

cellprofiler/modules/filterobjects.py
cellprofiler/modules/measureimageareaoccupied.py
cellprofiler/modules/measureobjectsizeshape.py
cellprofiler/utilities/hdf5_dict.py
setup.py

`h5py.highlevel` will be gone by 2.9, even if it returns in 2.8, so best to yank it out.

h5py 2.8 fixes

---

cellprofiler/modules/measureobjectintensity.py

A number of other equality checks for object_name_variable in this file check against value rather than the actual object.
#3622

#3622 Address potentially incorrect equality check

---

cellprofiler/gui/figure.py

The `set_label` call wasn't actually displaying anything useful on the gridview. I've changed this to `set_xlabel` (with a little more clarity) so the z-index is actually displayed. 
Here's before: 
And after:

Actually display Z-index on gridview

---

cellprofiler/gui/figure.py

Options taken from here: https://matplotlib.org/api/_as_gen/matplotlib.pyplot.scatter.html
This allows scatter plots to have customizable color maps and displays. For example, we have a custom module that finds two peaks within a 3D image. The previous histogram only allowed us to show the points in a single color:
With this change, we can now customize the color map to show the "chosen" points:

Add "c" and "cmap" as options for subplot_scatter

---

.travis.yml
cellprofiler/gui/imagesetctrl.py
cellprofiler/gui/pipelinecontroller.py
cellprofiler/modules/editobjectsmanually.py
cellprofiler/modules/filterobjects.py
cellprofiler/modules/loaddata.py
cellprofiler/pipeline.py
cellprofiler/setting.py
cellprofiler/utilities/hdf5_dict.py
cellprofiler/utilities/zmqrequest.py

Add [flake8](http://flake8.pycqa.org) tests to find Python syntax errors and undefined names.
__E901,E999,F821,F822,F823__ are the "_showstopper_" flake8 issues that can halt the runtime with a SyntaxError, NameError, etc. Most other flake8 issues are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree

Travis CI: Add flake8 to find syntax errors and undefined names

---

cellprofiler/utilities/check_for_updates.py

This message is often part of peoples' error messages on
GitHub/the forum, and it's a bit misleading. Since this site
is no longer maintained, we shouldn't let users know about this
error anyway.

Demote the update exception from warning to debug

---

cellprofiler/gui/editobjectsdlg.py

Without this change, it is a syntax error in Python 3

Explicit tuple required inside a comprehension in Python 3

---

cellprofiler/__main__.py
cellprofiler/analysis.py
cellprofiler/image.py
cellprofiler/pipeline.py
cellprofiler/utilities/zmqrequest.py
cellprofiler/worker.py
cellprofiler/workspace.py

Regarding StringIO, Queue, tread, and cPickle.
This doesn't fix any actual unit tests (yet), but it at least makes it so that the unittest can run at all!

Fix python 2/3 imports preventing python 3 tests from running

---

cellprofiler/gui/figure.py
cellprofiler/modules/displayhistogram.py
cellprofiler/setting.py

Resolves #3644 
I wanted to add a `log10` option, but it didn't make sense to do so because the bins in DisplayHistogram don't change, only the x-scale values. 
The usages of 'log' aren't exclusive to either natural log or log base 10 either, so I can't have `log` refer to just log10 or natural log. For instance, [`Axes.hist`](https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.hist.html) just says `log` and doesn't specify which one, whereas [`Axes.hexbin`](https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.hexbin.html) uses `log` to stand for `log10` :disappointed:.
Resolution: change the documentation to reflect that it is (and has been) performing the natural log.

Rephrase DisplayHistogram help to reflect that log aggregation is not base 10 but natural log

---

Pipfile
Pipfile.lock

This allows users to clone the repo, then run `pipenv sync` to get a reproducible, deterministic environment. Users can then run `pipenv run cellprofiler <headless-command>` to run cellprofiler (optionally using [the pipfile location environment variable](https://pipenv.readthedocs.io/en/latest/advanced/#pipenv.environments.PIPENV_PIPFILE) for running from a different directory).

Add a Pipfile for use in headless environemnts

---

unpinned_requirements.txt

I don't want to merge this until we have fixes for the failing `unpinned_dependency.txt` builds

Set numpy to be higher than the travis default (1.13)

---

cellprofiler/__main__.py

The error code that was returned from run_pipeline_headless was not being captured by the calling process. Additionally, an exception raised in a pipeline wasn't being caught as a failure inside the run_pipeline_headless block.
This was preventing us from capturing the exit code appropriately when cellprofiler failed on a run, since it would just emit a `0`.

Bubble exit code up from headless run for proper system reporting

---

cellprofiler/modules/correctilluminationcalculate.py

Resolves #2898 , as well as some other issues people had sent to me privately re: using median filter in illumination correction.  
The skimage median filter only works on ints, not floats (though it's on their roadmap to support floats), so SOME sort of transformation had to be done, but I don't understand why you would choose to rank-order the pixels rather than just make them an int.  If someone remembers/understands why and wants to argue strongly for why to do it on ranking, happy to listen, but otherwise I think this is a better solution.

Stop using rank ordered data for median filter

---

cellprofiler/__main__.py

This is ugly, and I'm very sorry about that, but it has to be called before bioformats is imported because bioformats checks if it can spin up javabridge upon import.  It also works to add this in the init if you find it less gross to have it there.

add JVM environment fix

---

cellprofiler/gui/figure.py

previously, the statusbar was giving errors, updated so that it works. fixed deprecation errors, and also updated so that the statusbar will only show information when the mouse is inside the matplotlib figures

Wxpython4 gui/figure.py's statusbar not showing fix

---

cellprofiler/pipeline.py

when exporting cppipe, it will no longer encode :|[]\ into \x__ sequences
also bumped up cppipe format versioning
This PR is meant to work in conjunction with PR https://github.com/CellProfiler/CellProfiler/pull/3766 but was separated to make it easier to scrap if incorrect.
@0x00b1 @AetherUnbound @bethac07

Export cppipe as text with no encoding

---

cellprofiler/modules/groups.py
cellprofiler/pipeline.py
tests/modules/test_loadimages.py

the only tests failing for test_loadimages are ones that are trying to access a invalid cellprofiler.org link with `HTTP Error 301: Moved Permanently` error

test_loadimages

---

cellprofiler/preferences.py

All preference set methods now use config_write.
config_write now has type-checking to use the correct write method, and it flushes after write.

Fix for issue #3857

---

cellprofiler/gui/pipelinecontroller.py

Fixes #1545, was very similar to #3873.

NamesAndTypes: "Next image group" ignores color/grayscale type

---

cellprofiler/modules/maskobjects.py
cellprofiler/workspace.py

Turns out the presence of an alpha channel value in the result from get_secondary_outline_color was causing this. It was fine in Python 2, but using this with numpy in Python 3 throws an error because of the extra data. This should be the only module in which this occurs.
Also corrected a h5py deprecation warning, didn't think it was worth another branch.

MaskObjects with objects is broken in Master

---

cellprofiler/modules/namesandtypes.py

Explained how to use a single object set in help, closes #1992.

Can't select Illumination Function or Objects NamesAndTypes set to All Images

---

cellprofiler/gui/editobjectsdlg.py
cellprofiler/gui/pipelinecontroller.py
cellprofiler/modules/definegrid.py
cellprofiler/modules/flipandrotate.py
cellprofiler/object.py

Resolves #1167.
I've made some fixes to get these modules running properly in CP4. I've made is so that manual editing popup windows will display the current cycle number in the titlebar, since these lack subplots which would show the normal title. This was already done for some of the modules.
While showing the full filename would be nice to have, this may not be trivial since these modules don't necessarily operate on an input image that has such a name. If that's in high demand it may be something to raise in the future.

Inform user which image is active for interactive modules

---

cellprofiler/modules/namesandtypes.py

Fixes #2095. NamesAndTypes was trying to add the global "manual bit depth" setting rather than the specific image's.

Can’t set "Manual" bit depth for more than one image

---

cellprofiler/gui/figure.py
setup.py

Resolves #2899 - in the figure window titles tend to overlap with axes and look bad.
As mentioned in the original thread, Matplotlib added a constrained_layout function to aid in displaying multiple subplots without elements overlapping. I've had a go at adding this to CellProfiler. There are some positives and negatives to this approach.
- Plot axes will no longer overlap with title text, instead maintaining a nice spacing.
- constrained_layout requires a predefined subplot grid rather than adding plots sequentially (As CP does). I've therefore made CP construct a GridSpec class when a module announces the number of subplots it needs. If this exists then plots will be applied to the GridSpec rather than straight onto the figure, allowing them to be laid out more neatly with the …

Fix figure display padding issues

---

cellprofiler/gui/moduleview.py
cellprofiler/gui/pipelinecontroller.py

Fixes #3839
Notes aren't considered as a 'real' setting and so only changing notes in a pipeline wasn't registered as something to save. I've made editing notes trigger part of the settings event handling sequence. This might not be particularly slick but works without having to give notes all the attributes proper settings have.

Notes don't save in 3.1.8

---

cellprofiler/gui/editobjectsdlg.py

A temporary objects matrix for running 'undo' was being constructed with the wrong shape. Should now match the main matrix used to store objects. I think that fixes #3683 and fixes #3814

Weird behavior in EditObjectsManually "Undo" button

---

cellprofiler/modules/crop.py
cellprofiler/modules/resize.py

Resolves #3387. Forcing the same zoom levels tends to confuse users as it looks like the original image has been cropped or resized inappropriately. It's not immediately obvious that they can pan the original image and it's only showing the cropped area at the scale of the result image.

Unlink subplot axes in Crop and Resize module results display.

---

cellprofiler/gui/pipelinelistview.py

It seems that on mac dragging a module returns a wx DragCopy object rather than DragMove. On Windows this can be triggered by holding control when dragging, which does sometimes happen when selecting and moving multiple modules quickly.
This will disable module duplication by ctrl+drag, but fixes moving modules by dragging on mac. If ctrl+drag duplication was precious perhaps we could try making this OS-specific?

Prevent module duplication when dragging on mac

---

cellprofiler/setting.py

Fixes #3756.
For some reason the 'Elsewhere' option when selecting a file was set to fetch the current directory CellProfiler is running from as a base path. This causes problems on Windows as CP's workers don't have permissions to write to those folders.
When a path is generated CP attempts to join a starting directory to whatever the user entered in the subfolder box. Given that 'Elsewhere' should be a full folder path rather than just a subfolder, I've added a little more validation to check that whatever the user entered actually functions as a path on it's own. This still won't fully check write permissions because Windows, but it's at least a sanity check.
I've also changed the default 'starting' directory for 'Elsewhere' from the working directory to the default output folder. This …

ExportToSpreadsheet tries to write into wrong folder

---

cellprofiler/gui/moduleview.py
cellprofiler/gui/namesubscriber.py

Closes #2363. Closes #3726.
This is a common problem seen when training users - using the scroll wheel while hovering over a dropdown menu will change the selected item. Users tend to scroll down module settings panels quickly and accidentally change settings while doing so because of this. This change will ignore mousewheel events over such widgets.

Disable mousewheel on dropdown menus

---

cellprofiler/gui/cpframe.py
cellprofiler/gui/pipelinecontroller.py
cellprofiler/gui/pipelinelistview.py

Resolves #3878 
Currently the right click menus on the module list allow a user to duplicate/delete/disable a module, however if multiple modules are selected some of these functions operate on all selected modules while others only edit the active module.
This change makes it so that having multiple modules selected will apply operations to all of them. To avoid menu clutter having multiple selections will only give context menu options that operate on multiple modules.
When selecting a single module I've also added a module's name to the menu options. So you see "Delete IdentifyPrimaryObjects (#4)" rather than "Delete Module 4". This should make it clearer which module is being operated on.

Add context menu for handling multiple modules in pipeline list

---

cellprofiler/pipeline.py
cellprofiler/workspace.py

Closes #3196.
The pipeline in question was still throwing errors when trying to use "Max of all images". The pre-group workflow involves creating temporary workspaces for each module to figure out which images and stats will be generated, but this wasn't passing down any grids made as these aren't proper measurement groups. This would trip up on IdentifyObjectsInGrid since the temporary workspaces would be lacking the necessary grid maps. I've (a bit clunkily) allowed the pipeline pass grids between temporary workspaces to fix this issue.

Make prepare_group work with grid modules

---

cellprofiler/gui/pipelinecontroller.py

For some reason comparing a yes/no setting class to a string returns True, which broke settings updates. Sorry! This should be more robust.

Fix settings bug

---

cellprofiler/modules/identifyprimaryobjects.py

Closes #3907
As suggested by @DeboraOlivier, advanced users would appreciate seeing more information to fine-tune their declumping parameters more quickly. I understand that we don't want to overcomplicate the settings and output window so I've just added maxima for now. While this won't display intermediate filtering steps as proposed, seeing the detected maxima should give a better idea of what those steps are doing and doesn't add large numbers of options to an already complex module. This setting will be disabled by default.
I've made the colour customisable but have that defaulting to blue. As maxima tend to be 1 pixel spots there's no single colour that will show obviously against both bright and dark backgrounds without zooming in, but this seems to make a nice compromise.

Add ability to display accepted maxima to IdentifyPrimaryObjects

---

tests/modules/test_relateobjects.py

Looks like something went badly wrong when merging #3832. Some of the tests weren't converted into class methods properly and others were duplicated. I believe I've got them all working again.

Fix RelateObjects Tests

---

cellprofiler/gui/pipelinecontroller.py

Closes #2514. Modules can be moved without triggering major errors and this is already the case when dragging, so the forced exit seems unnecessary.

Disable exit from test mode when moving modules.

---

cellprofiler/setting.py

Fixes #3929. Python 3 exceptions don't possess a .message by default.

Fix pipeline list view error warnings

---

cellprofiler/gui/pipelinecontroller.py

Fixes #3864. It turns out that trying to undo actions immediately after creating or loading a workspace would also break the undo button until CellProfiler is restarted. I've made it so that creating a new workspace clears the undo buffer.

Reset 'undo' functions when creating a new workspace.

---

cellprofiler/__main__.py

Closes #3872.
For the sake of keeping CellProfiler stable despite any future changes to Java, I'm proposing that we make Windows default to using the packaged environment specified by CP_JAVA_HOME, then use JAVA_HOME if it's absent (it's currently the other way around). This lets users specify a custom version by unsetting CP_JAVA_HOME, but avoids the risk of a brand new install trying to pull an incompatible Java version.
Perhaps more importantly, I've added a more informative error when launching CP if these variables aren't set at all. In the current release a "java not found" error flashes in the console and then the console closes before the user can read it. This change will display a message plus a link to some Windows troubleshooting instructions, then hold the console open until …

Revise Windows Java detection

---

cellprofiler/modules/rescaleintensity.py

Fixes #3506.
I considered just adding a warning when trying to use a color image with this module, but it turns out that all the modes aside from 'stretch intensity' already worked just fine with color images. You might also imagine a scenario where a user wants to rescale their channels before splitting them.
I've made it so that if the input image has multiple colour channels the 'stretch intensity' mode will be applied to each channel individually. An alternative solution might be to have max intensity across all channels considered as the stretching 'target'. Either is better than the module just breaking when you do this.
I also noticed that the output display for RescaleIntensity was the default viewer. Since this includes intensity normalisation prior to display it seems to make it …

Fix RescaleIntensity crashing when told to scale a color image

---

cellprofiler/gui/cpframe.py
cellprofiler/gui/pipelinecontroller.py
cellprofiler/modules/groups.py

Fixes #2549. Related to #3873.
The logic in the original version of these commands was a bit weird.
It attempted to select a random image group but never actually set that group up to run, so random numbers were generated based on the length of a random group what wasn't running. I expect this is why the % operation was needed - so that if the proposed index was too high you'd still get a valid result, but this would then bias you towards low index numbers.
It also seems that in modern numpy specifying size=1 in numpy randomint forces it to return an array rather than a single int.
To resolve this I've revised the randomisation approach and split random into two functions - Random Image Set and Random Image Group. These use separate menu buttons. Random image set will now only randomise …

Fix Random Image Set, add Random Image Group

---

cellprofiler/modules/measureobjectsizeshape.py

A typo in the help text was injecting "System Message: WARNING/2 (<string>, line 47)" into the help section of this module.

Fix measureobjectsizeshape help

---

cellprofiler/modules/correctilluminationapply.py
cellprofiler/modules/identifysecondaryobjects.py
cellprofiler/modules/identifytertiaryobjects.py

Closes #1977.
I've gone through and added checks for whether image dimensions are compatible to modules where this wasn't already handled elsewhere.
In the case of IDTertiary, the module actually has some methods for handling when initial object sets are larger than the smaller objects, but this isn't something the user should be doing intentionally. I've therefore made the error simply ask that the dimensions be matched if this process was unsuccessful.

Add more descriptive errors to modules requiring matched image dimensions

---

cellprofiler/gui/cpframe.py

Closes #3334, Closes #3359 and Closes #3735.
By somewhat popular demand, this menu button should now work. I've made it OSX-specific as opposed to OSX and Linux.
I've also moved the menu button to a more sensible spot rather than having it between the two pipeline running options.

Fix "Open A New CP Window"

---

cellprofiler/gui/preferencesdlg.py

Related to #3857.
I'm not sure if anyone has verified the original issue on Linux or if it's already fixed, but on Windows there are no problems with saving. However, the current GUI does not make it obvious that preferences changes will only save when exiting the dialog with the "OK" button. I know this has tripped me up in the past. To address this I've just changed the text on that button to "Save", which will hopefully be more intuitive.
Could someone check that this works fine on Mac? I believe there's a chance that the button order may be reversed with "OK" on the right, in which case I'll add a less lazy solution.

Relabel "OK" button in preferences GUI

---

cellprofiler/__main__.py

urlparse was renamed to urllib.parse in Python 3, so imports from #3958 need to be fixed

Fix urlparse in Python 3

---

cellprofiler/modules/flagimage.py
cellprofiler/modules/measureobjectneighbors.py

Minor bug from #3876, also found another occurrence in the new measureobjectneighbours module version.

Fix "Yes" in settings help

---

cellprofiler/modules/imagemath.py

Fixes #3307.
When loading a pipeline, an ImageNameSubscriber inserts it's value into the list of options if it's not found in the list of possible images. When creating this class providing no setting value will default to 'None', which makes it clear to the user that no image was selected. However, ImageMath was creating subscribers with a default of "" (blank string). This makes the combobox appear blank on Windows, but it appears that on Mac this might make a combobox default to showing the first "proper" option if there is one, and this is done without internally modifying the setting value.
The result is that a pipeline would display the wrong setting as being selected when first creating the module, and if this was not changed before the user ran or saved then the pipeline would …

Fix ImageMath "Image is missing" error when loading pipelines

---

cellprofiler/modules/exporttodatabase.py
cellprofiler/modules/exporttospreadsheet.py

I've made it so that ExportToDatabase will no longer try (and fail) to rescale boolean thumbnails. Fixes #3976
On the subject of thumbnails, I've made ExportToSpreadsheet exclude thumbnails generated by ExportToDatabase, unless the user is in 'choose columns' mode - in which case they can have them if they so wish. Fixes #3973
I've also added the requested 'add file folder and name in objects table' option to ExportToSpreadsheet. Closes #3739
These are a bit tricky to test on the part of Master's analyse mode being broken, but I've got them working on 3.1.9 and hopefully the port should be fine.

Fixes for export modules

---

cellprofiler/gui/addmoduleframe.py

Closes #3964.
This pull request changes the 'Add Modules' panel so that typing in the search box automatically displays a filtered list of modules which have names matching the entered text (case-insensitive for convenience). By default the first match is highlighted, and I've made it so that hitting 'enter' will add that selected module. This means that you can now add specific modules using just the keyboard e.g. Type "water" and hit enter and you'll add the Watershed module to your pipeline.
To preserve the old functionality, I've left the dedicated 'search' button in place. Pressing this button will still grab whatever was in the text box and search all help for mentions of the term.
Edit: Attaching a screenshot -

Add search filter when adding modules

---

cellprofiler/modules/resize.py

Fixes #3831, closes #3952. Turns out you no longer need to rescale intensity to between -1 and 1 when resizing in the current version of Skimage. Yay.

Fix loss of precision when resizing images

---

cellprofiler/gui/pipelinecontroller.py

The from_matlab parameter is no longer needed.

Fix 'duplicate module' function.

---

cellprofiler/gui/moduleview.py

Fixes #3945.
As per the issue thread, test mode would sometimes fail to properly set the test mode flag, which causes problems in some pipelines (most notably the example pipeline!). This was happening on the validation thread - test mode flags were also set on this thread. This can confuse CellProfiler since I think stale validation tasks sometimes managed to change the test mode flag before being cleared. Removing the code which does this doesn't bring back the original issue it was added for (#411) - we appear to be using a different threading system now anyway. Validation still seems to work properly so hopefully this is all good now.

Fix pipeline failing to enter test mode properly

---

cellprofiler/gui/imagesetctrl.py

A problem we have is that CP3 .cpproj files have their measurements, particularly filenames, encoded as bytes rather than strings when the HDF5 data is imported in Python 3. I'm still trying to figure out how best to address this, but for now these changes decode elements needed by the GUI as necessary.
Posting this as a draft in case anyone has a better idea, I'm still trying to figure out how to deal with this in analysis mode.

Fix loading of CP3 workspaces

---

cellprofiler/gui/pipelinecontroller.py

Seems like this was just a visual issue, it just needed a forced update.
Fixes #3897.

Fix test mode/analysis buttons not activating when analysis aborts due to error.

---

cellprofiler/modules/expandorshrinkobjects.py

I believe this should fix #3645.
ExpandOrShrinkObjects was set up to independently shrink objects in the .segmented, .unedited_segmented and .small_removed_segmented object arrays. The IdentifySecondary module (and possibly others) requires that objects appear on both segmented and unedited_segmented. Normally this isn't a problem, but when shrinking objects those which previously had holes filled can have slightly different center points. They therefore don't align in IDSecondary and get excluded.
To address this I've made ExpandOrShrinkObjects apply results from the segmented set to the unedited sets. This should allow the centers for the extra objects to be found, while producing a consistent segmentation for the objects which were carried forward.
This seems to fix the issue in my …

Fix loss of objects when running IdentifySecondaryObjects after ExpandOrShrink

---

cellprofiler/gui/figure.py
cellprofiler/gui/help/__init__.py
cellprofiler/modules/threshold.py
cellprofiler/modules/unmixcolors.py

Fixed a bunch of issues effecting the figure window which were found during RC testing:
- Wrapped excessively long figure names. Constrained layout will scale the graph to fit the whole title into the window, which made figures with titles such as file paths get too small.
- Made subplots from UnmixColors arrange themselves into rows of 3. This should make for a sensible display with any reasonable number of channels being isolated. Other modules with flexible numbers of figures already handle this.
- Moved Threshold's stats table to a second row to reduce crowding.
- Fixed a bug with constrained layout when trying to display individual subplot windows.
- Made histograms work.
- Fixed console spam when the Measure Length tool was moved off the focused subplot.
- Fixed the Measure Length …

Figure display fixes

---

cellprofiler/gui/pipelinelistview.py

This pull request aims to restore the dividing line between the input and pipeline modules (as requested). This feature seems to be absent in 3.1.9 too, but I've tried to restore the visual distinction using a border on the input box sizer. Unfortunately I can't change the colour of the border so it matches the rest of the interface rather than being a black line, but it should still be a bit more obvious that the input modules are seperate.
I've also addressed the extra blank space between the input and pipeline modules which appeared in 4.0. I'm not sure why this happens, but in WX4 the widget seems to want to add space for an extra item to be added. I don't know whether this is a Windows-specific issue, so could someone check how this looks on Mac before merging?

Restore input/pipeline module list boundary and correct alignment.

---

cellprofiler/gui/editobjectsdlg.py

Matplotlib are in the process of moving away from creating a wx statusbar (see matplotlib/matplotlib#17092). For the time being the current version attempts to update whatever wx statusbar is present on a plot window. I'd fixed this for the normal figure windows, but on the edit object dialogs there is no statusbar at all which upsets matplotlib.
As a fix for this version, I've added a dud function to chuck out the update commands sent by matplotlib.

Fix console spam in EditObjectsDialog

---

cellprofiler/gui/datatoolframe.py
cellprofiler/gui/parametersampleframe.py
cellprofiler/modules/saveimages.py
cellprofiler/modules/trackobjects.py
tests/modules/test_exporttodatabase.py

Linked to CellProfiler/core#4. This legacy parameter didn't do anything and had been partially removed from core, causing problems with TrackObjects.

Remove deprecated can_overwrite measurements parameter

---

cellprofiler/modules/classifyobjects.py

The NumberConnector class was used to specify a dynamic minimum value for the upper threshold, but it doesn't seem to work properly in Python 3. Since it's only used in this module, and even then only once, I've replaced it with standard validation in validate_group and upon execution. Sensible settings should be obvious enough to begin with so there's no need to be fancy.

Fix ClassifyObjects validation.

---

cellprofiler/gui/help/search.py

Requires CellProfiler/core#6.
The search function spends a lot of time converting every module's help text into HTML before searching for the user's keyword. This pull makes CP fetch the raw help text from each module and do a preliminary scan on that to determine which modules actually need a full fat search performed on them. At least on Windows this dramatically speeds up the function.

Improve "Search Help" speed

---

cellprofiler/gui/regexp_editor.py

Fixes #4039
This should make the regex window behave and look sensible with WX4. Could someone check how this looks on Mac?

Fixup Regex editor for wx4

---

cellprofiler/modules/identifyprimaryobjects.py
cellprofiler/modules/identifysecondaryobjects.py
cellprofiler/modules/threshold.py
tests/modules/test_threshold.py

Requires CellProfiler/core#7.
Closes #3953.
Probably fixes #3738.
This is a rewrite of the Threshold module to make things more consistent. Key changes are:
- When writing measurements, "Original Threshold" will always be the uncorrected threshold, while "Final Threshold" will refer to the corrected threshold with multipliers and limits applied. "Guide Threshold" has been added to record a global threshold which was used to constrain an adaptive threshold.
- MCE and RobustBackground are now available as adaptive threshold methods.
- Skimage methods are now used wherever possible. RobustBackground is unfortunately not available but the other methods were. We're still using centrosome's block-based adaptive thresholding as the skimage local_threshold function currently performs very poorly …

Revise Threshold module

---

cellprofiler/modules/imagemath.py
tests/modules/test_imagemath.py

Fixes #4071
I think this is a sensible way to do this. "Difference" mode will still replicate the old XOR functionality.

Make ImageMath 'subtract' boolean arrays

---

cellprofiler/modules/measureobjectneighbors.py

As raised on Slack, MeasureObjectNeighbors had miserable performance when using larger expansion distances. I found that this was a problem with scipy.ndimage's binary_dilation function (mentioned [here](https://github.com/scikit-image/scikit-image/issues/1190)).
However, per [this thread](https://stackoverflow.com/a/51159444), it's possible to achieve the same results using the Fast Fourier Transform. In my testing this gives us exactly the same results with a substantial increase in speed and better memory usage. The caveat to this is that it's marginally slower when working with small images and structuring elements, although at that size the overall time taken is relatively small to begin with. 
Some testing results on 1 image, with 250 objects:
- Old method, 1 pixel dilation - 0.375s …

Implement fftconvolve in place of binary_dilate for MeasureObjectNeighbors

---

cellprofiler/gui/figure.py
cellprofiler/modules/expandorshrinkobjects.py
cellprofiler/modules/identifytertiaryobjects.py
cellprofiler/modules/maskobjects.py
cellprofiler/modules/relateobjects.py

Fixes #3956 
By default matplotlib generates a 256 colour colourmap for displaying figures. We shuffle this map, but it still gets stretched when handling large numbers of labels, resulting in neighbouring objects being assigned similar colours. We can solve this by supplying the `lut` parameter in the cmap call to specify how many unique values we need.

Add true randomisation of figure colourmaps

---

cellprofiler/gui/pipelinelistview.py

At the moment, duplicating or moving multiple modules upsets the GUI as CellProfiler tries to display the settings panel for each module as it's 'added'. This change makes it so that an added module is only activated if a single module was selected, which is typically the case when adding to the pipeline or moving a particular module of interest. This makes operations on multiple modules much smoother.

Disable module activation when operating on multiple modules

---

cellprofiler/gui/figure.py

Also fixed some potential console spam when clicking rapidly.
This won't measure length in 3D, but apparently some people still wanted to do 2D size measurements on single planes.

Enable figure 'measure length' function in 3D mode

---

cellprofiler/modules/exporttospreadsheet.py

I believe we now handle decoding when reading settings, so this extra en/decode step that we added when setting up core has started causing problems.

Fix ExportToSpreadsheet settings upgrade

---

cellprofiler/gui/addmoduleframe.py

I think someone suggested this when I was making #3971, but I thought it might be tricky. I've been enjoying the quick search so much that I had a go anyway.
Changes are as follows:
- "Add Modules" launches with the search box focused by default. This has no real impact if you're not using it, but allows you to type straight away.
- While the search box is focused, pressing 'Escape' will close the 'Add Modules' window.
- While the box is focused, the 'Up' and 'Down' arrow keys can be used to highlight the desired result.
- 'Enter' adds the highlighted module to the pipeline.
This allows you to add modules entirely with the keyboard, which can be pretty fast.
Might be worth checking that these keys don't interfere with anything on mac, although I'm not expecting problems.

Add more keyboard shortcuts to 'add modules' window

---

cellprofiler/modules/__init__.py
cellprofiler/modules/combineobjects.py
tests/modules/test_combineobjects.py

Continued and rebased from #4061, since module loading was changed.
I've now added tests. In it's current state this module is not compatible with 3D object sets, is making that happen a priority?
---
Resolves #2140
Bringing back the idea from #2151.
I've gone for trying to keep this relatively simple for now. Some of the methods could probably be more efficient, but it seems to work. The general idea for this module is to allow people to combine two object sets into a single set, which is primarily useful if you needed different detection settings for different objects within the same image.
At present I've added 4 methods of handling overlapping objects, as follows:
- Merge - Touching objects are assigned the label from the first object set. When touching multiple objects each pixel is …

Add CombineObjects module

---

cellprofiler/gui/metadatactrl.py

Hopefully fixes #4085
It looks like in WX4 an `EVT_SHOW` event is generated for both a module and the window itself. I think this meant that if you were leaving a module with a MetadataControl filed, the module event would delete the controller but the Window event would then try and fail to fetch it again. Ignoring the Window events seems to fix it. Might be helpful if someone could verify this on Mac.

Fix inappropriate calls for MetadataControl when leaving module view

---

cellprofiler/gui/pipelinelistview.py

Fixes #3966
It turns out that `ScreenToClient` can sometimes return outdated mouse coordinates if the user moves the mouse and clicks a module too fast. This was making CellProfiler inappropriately try to drag and drop the targetted module rather than viewing it. Since the target module was deleted and replaced with a copy, this would make the settings fail to show.
To fix this I've made the drag/drop start position get set using the x, y coords sent over from the other functions. I've also made it properly check and ignore dropping to the same position in the pipeline (no valid change).

Fix module list view drag behaviour

---

cellprofiler/modules/measureobjectsizeshape.py
tests/modules/test_measureobjectsizeshape.py

Resolves #3571. Resolves  #3498. Fixes #3841. Requires CellProfiler/core#19. Rebased/cleaned up from #4099.
I've had a go at trying to explain the new metrics simply, any further ideas would be very helpful.
---
The aim of this pull request is to migrate towards using Skimage regionprops functionality within the MeasureObjectSizeShape module. This provides some performance improvements but more importantly gives us access to a series of new measurements. We were already using regionprops in 3D mode.
I've added a new setting called 'Calculate the advanced features?' to allow users to enable/disable some of the new features. In 2D mode this toggles the 'Moments' features, since these produce an excessive number of potentially unwanted results columns. In 3D mode the setting currently …

Rework MeasureObjectSizeShape to use new regionprops measurements

---

cellprofiler/gui/cpframe.py

It looks like the BioFormats reader cache is normally cleared when leaving test mode, or when a headless CP instance exits, but not if you quit the GUI without leaving test mode. Adding a step to the exit workflow seems to fix the exception spam when exiting, might be worth verifying this on Mac.
I'm also not sure if the original exit workflow will work properly in headless mode.

Fix exceptions when trying to exit CellProfiler while Test Mode is enabled.

---

cellprofiler/gui/moduleview.py

Resolves #3978
Been looking into some other issues with table display and figured out how to do this. Pretty basic but hopefully functional. Someone should verify this works properly on Mac, as always.
Clicking a column header should make the table sort itself based on that column

Add column sorting to the metadata table

---

cellprofiler/gui/moduleview.py

Fixes #2738
At least on Windows, once a module view refresh was triggered (5 seconds after typing) the regex text boxes in the Metadata module became completely unresponsive to user input (related to #3104).
Allowing event processing to continue after `on_kill_focus` appears to resolve this problem and allows further editing after a settings refresh.
On top of this, I've added an option to disable a text box's timed module refresh and used this to disable such refreshing specifically for the regex fields. It often takes more than 5 seconds to write an expression and so the refresh could disrupt input. Since the regex fields don't directly impact other module content I don't think the lack of a refresh will cause any problems.

Fix Metadata regex field behaviour

---

cellprofiler/modules/savecroppedobjects.py

Needed this for a project so it's a quick fix for now. Skimage won't allow you to supply an intensity image with more dimensions than the object mask, but if we're working in 2D we can just use the same mask for each channel. Saving takes longer in RGB mode and isn't as versatile as SaveImages, but I think it's an improvement.
I've also disabled the 'low contrast' warning that Skimage IO puts out if an image is dim, since that gets really annoying when exporting 2000 images.
Documentation also appears to have been incorrect, so I've updated it.

Make SaveCroppedObjects compatible with color images

---

cellprofiler/gui/namesubscriber.py

This PR should restore the ability to right click a NameSubscriber and see a context menu listing available images/objects by their source modules. I think this is actually a pretty useful feature when working with complex pipelines.
The original functionality was removed/broken in #3490, I think because a new wx item ID was generated for every menu option each time a module was viewed, which eventually exhausted all possible IDs.
I'm not sure how to properly 'free up' wx IDs, it seems like once an ID is generated the `NewId()` function just continues counting up regardless (so it'll hit the limit regardless of the ID not being used). Instead I've had the menu generate it's own local index and use that. Since the menu is destroyed immediately after use it doesn't seem to conflict with …

Fix NameSubscriber right click functionality

---

cellprofiler/gui/module_view/_module_view.py
cellprofiler/gui/pipelinelistview.py
setup.py

Hopefully backwards compatible.
Things to test on OSX:
- Dragging a module moves it. Module persists when activated.
- Dragging while holding `control` duplicates that module at the targetted position.
- Dragging to somewhere else on the window (not the pipeline list) does not delete modules.
- Dragging to a second CP window moves the module from one to the other, deleting it from the source window (with ctrl it should copy). Pipeline then doesn't revert when a module is activated.
This may also finally enable moving AND duplication on OSX, since we'd disabled the latter.

Fix for pipelinelistview drag/drop functionality with wx 4.1

---

cellprofiler/gui/pipelinecontroller.py
cellprofiler/gui/pipelinelistview.py

Closes #2601.
I've added this to make using the pipeline list a bit clearer to new users. Are we happy with this text?
I've also made it so that double clicking on the pipeline list will open the 'add modules' window if you aren't clicking on an existing module.
Also fixed a bug where the step function would try to run when not in test mode. The icon was invisible but still tried to do things.

Prompt users to drag & drop pipelines to get started

---

cellprofiler/modules/graytocolor.py
tests/modules/test_graytocolor.py

Closes #3538
In this PR I've added an optional setting to GrayToColor to rescale the input images to the 0-1 range prior to merging. This is done by dividing each channel by it's maximum.
For the moment I've made it do this before applying the multiplication factor specified by the user. In theory the user can then use a factor <1 to balance the brightness of the channels as they wish (or deliberately blow out the intensity for some reason).
Hopefully this'll be pretty useful, since it avoids the need to run a rescaling module before making such overlays.
New copies of the module will default to having rescaling enabled. Upgraded pipelines will keep it disabled for compatibility.

Add rescaling to GrayToColor

---

cellprofiler/gui/figure.py

Resolves #2446.
This PR replaces the right click submenus for adjusting figure contrast with an all-in-one popup. Right clicking a figure plot now has an option labelled "Change Contrast" which brings up the following tool window:
Within this you can change the normalisation mode, intensity display limits and normalisation factor (for log and gamma modes). The sliders represent a 'sensible' range, but these bounds can be exceeded by entering values into the boxes next to them. Changing these settings should update the plot immediately to give an instant preview.
I've also added an 'Apply to all' button. This will grab the display/normalisation settings and try to apply them to other subplots in the same window which are displaying an image... so that you don't have to repeat the process …

New figure contrast adjustment dialog

---

cellprofiler/gui/pipelinecontroller.py
cellprofiler/gui/pipelinelistview.py

Currently CellProfiler automatically displays each module's settings panel as it runs in Test Mode. Particularly when using 'Run' across multiple modules, this results in the settings panel rapidly redrawing for each module. It looks like this interface rendering actually slows down test mode quite a bit, since the drawing has to finish before the next module executes.
In this PR I've disabled the call to display a module's settings when it executes in test mode. This makes using 'Run' much smoother. This also applies to the 'Step' functionality, but in my view it's more convenient to not have to keep re-selecting a module when trying to tweak it's settings. Since we now have better control over stepping from specific modules, keeping the current settings panel open might make more sense. …

Disable automatic module activation when running test mode

---

cellprofiler/modules/saveimages.py

Fixes #4014, Fixes #4015.
This PR makes SaveImages respect bit depth in 'movie' mode. 'Movie' mode has also been renamed to 'Movie/Stack' mode, and the user now has an option to specify whether to save their frames along the T or Z axis. 
All bit depths seem to work smoothly, so there was no need to adjust which are available.

Improve SaveImages stack functionality

---

cellprofiler/gui/editobjectsdlg.py

Fixes #3862.
The previous setup for handling right clicks was a bit messy. On mac `EVT_CONTEXT_MENU` likes to fire any time you ctrl+click, whereas on Windows it only fires if other events weren't triggered. To solve this we've made the context menu activate only when not clicking on an object within the figure, as part of the normal click flow. This does mean that the right menu can now only be accessed by clicking on the figure itself, but that also prevents the right menu from opening when clicking on objects on Mac.

Fix edit objects manually right click conflict

---

cellprofiler/modules/measureobjectintensitydistribution.py
cellprofiler/modules/measureobjectneighbors.py

This PR makes modules which display objects coloured by data values use a more sensible (linear) colormap by default.
In the case of MeasureObjectNeighbours, it'll no longer use the default (random) map when colouring by number of neighbors. The map was/is only customisable if you enable retention of the plot as an image, so I think a better default makes sense.
In MeasureObjectIntensityDistribution the same applies to heatmaps, and I've also disabled colorbars on this module since they really don't play well with the WX table plot.

Set sensible colormap defaults

---

cellprofiler/modules/measuretexture.py
tests/modules/test_measuretexture.py

Resolves #3386 .  
This PR allows you to adjust your grey levels before running texture feature extraction; it doesn't look like this produces an exponential speedup though, just about 3x in my (very limited) tests going from 256 grey levels to 2, and almost no appreciable speedup at all going from 256 to 8.
I think the slowdown actually didn't come from the change in gray levels, but from the fact that in 2.X we run [all objects at once](https://github.com/CellProfiler/CellProfiler/blob/stable/cellprofiler/modules/measuretexture.py#L564-L568) and in 3.X we run [one object at a time](https://github.com/CellProfiler/CellProfiler/blob/v3.1.9/cellprofiler/modules/measuretexture.py#L608-L619); image texture features are still pretty fast in 3/4, no matter what the number of gray levels.  I'll …

Bin grey levels before running MeasureTexture

---

cellprofiler/gui/constants/figure.py
cellprofiler/gui/figure/_figure.py
cellprofiler/gui/utilities/figure.py

This PR replaces the 3x3 grid-based plots for 3D images with a single plane view accompanied by a slider for switching plane.
The plots will initialise with the middle plane displayed, and users can click/drag the slider or use dedicated buttons to change the displayed plane. Normalisation is calculated across the entire stack (thanks Allen!). The buttons don't really position well with `constrained_layout` and had to be done manually, so they'll only display with up to 2x2 subplots.
Buttons can also appear underneath (rather than above) the slider on the top row if you have 2 rows of subplots with sliders. Not sure if there's a better solution because plot size can be different if you have tables on the bottom row, but it looks acceptable with everything I could find. Fortunately very …

New 3D viewer

---

cellprofiler/modules/measuretexture.py
setup.py

Dask has some problems with semaphore objects, we should probably hold off on this functionality for now, and perhaps have it as an optional setting in a future release.
Fixes #4151, fixes #4143

No Dask :(

---

cellprofiler/modules/measurecolocalization.py

Resolves #4168 somewhat.
MeasureColocalization uses a loop for determining the Costes Automated Threshold. This involves serially decreasing a 'test threshold' value and evaluating whether it brings the Pearson r value below 0. On large images this starts to seriously impact performance as, while a single test is quick, testing every possible value is very intensive.
In this PR I've added a setting to choose whether to use a "fast" or "accurate" mode for this calculation. New module instances default to 'fast', upgraded pipelines default to 'accurate'. In "fast" mode, we decrease the test threshold by a larger amount each loop if the r value was far above 0. This should 'home in' on the correct threshold and cut out some additional work. In my testing this strategy gave the same final …

Add setting for faster Costes thresholding

---

cellprofiler/modules/medianfilter.py

Noticed this while testing the 3D pipelines. We'd been using `scipy.signal.medfilt` instead of `scipy.ndimage.median_filter`. The former is much slower and this is particularly noticeable with large window sizes.
In my testing switching produced exactly the same results with about a 6-10x speed improvement. The unit tests also still pass. As a bonus the `ndimage` function doesn't require an odd number for the window size, so I've been able to open that up to accept any integer.

Faster MedianFilter module

---

cellprofiler/gui/pipelinecontroller.py

Fixes #4177
On Windows, the first line in a progress dialog is formatted as a header. This was causing sizing problems.
To address this, the message now starts with a newline character. I've also added a line break between the file name text and the elapsed time counter. Also needed a call to `Fit()` when updating, because at least on Windows the `ProgressDialog` class seems to ignore calls to `SetSize`. How annoying.

Fix bulk file loading dialog on Windows

---

cellprofiler/__main__.py

Since Pyinstaller is not completely up to date for Python 3.8 and Matplotlib, starting CellProfiler unavoidably prints a bunch of deprecation warnings as part of the Pyinstaller startup script.
A possible solution here is to clear the console log once we reach CellProfiler code (only when running frozen, obviously). I also made it print that we're starting CellProfiler, alongside the version number, which might help with the "What is this blank console Window doing?" effect and also gives us a little more troubleshooting info if something goes wrong.

Cleanup startup of frozen app

---

cellprofiler/gui/module_view/_joiner_controller.py

Resolves #4027
Per @ErinWeisbart's request, because this was indeed annoying and it's a simple fix. This PR makes selecting a metadata matching key automatically populate any other empty fields in that row with the same key (if it's available for that item).
I figure there's no need for a dedicated button, if the cells aren't empty they'll be left alone, and if there's an exactly matching key then users will in most instances want to use it.

Make metadata matching auto-fill empty columns

---

cellprofiler/gui/pipelinecontroller.py

The artist currently can't handle 3D images (it was originally made before volumetric pipelines were a thing). It'll probably take some work to get it fully functional, so let's disable WSV in 3D mode for now.

Disable WSV when in 3D mode

---

cellprofiler/modules/threshold.py

When using an adaptive threshold, we'll use 2-class otsu on blocks which only contained two unique values.

Handle adaptive 3-class otsu on blocks with only 2 values

---

cellprofiler/gui/figure/_figure.py
cellprofiler/modules/correctilluminationapply.py

Fix #4228
Figures with excessive numbers of subplots are still cramped, but I've made CellProfiler use a smaller font size when a row or column will contain more than 3 plots. This should leave the plot visible.
I've also tidied up the formatting for CorrectIlluminationApply's plot titles. It now rounds properly and uses a shorter label for the middle plot when we have a lot to display.

Adjust Figure parameters to handle large numbers of subplots

---

cellprofiler/gui/_welcome_frame.py

WebView on OSX has a habit of trying to affix "file://" to our custom navigation calls. The correct navigation event is sent first, then the dodgy "file://" events are also sent. Ignoring these events appears to fix it.
Fixes #4219

Fix Welcome Screen on OSX

---

cellprofiler/gui/app.py
cellprofiler/gui/checkupdate.py
cellprofiler/gui/help/menu.py
cellprofiler/gui/preferences_dialog/_preferences_dialog.py

This PR adds a system to automatically check for and notify the user of updates when running frozen builds of CellProfiler.
A setting has been added to the preferences dialog (default:Enabled), and a "Help-->Check For Updates" menu option has been added to allow users with this function disabled to force an update check.
Once per week on app startup, this system will check the version of the latest GitHub release and show the notification below if they're running an older version. Date of the last update check is stored within the config key.
I've added a bit of code to catch errors which could happen with the web request. If running from startup errors are printed to the console. If the user activated the check using the menu option instead they'll get a dialog with the relevant message, …

Add automatic update notifications

---

cellprofiler/modules/calculatemath.py

"Objects" selection was displaying a object name entry widget rather than object selection widget. A duplicated line was causing wx layout errors.

Fix CalculateMath errors

---

cellprofiler/gui/pipelinecontroller.py

I'm not sure this ever actually worked properly, since the traceback module doesn't seem to accept a logger as an argument.
This should update the analysis event handler exception handling to work properly.

Replace broken Python 2 analysis error handling

---

cellprofiler/gui/pipelinecontroller.py

Requires cellprofiler/core#53
It's a bit messy, but this should provide pipeline data in Sentry errors logged from the main app thread. This will be super helpful for figuring out problem settings.
Sentry has some weird limits on container sizes which aren't immediately obvious. We override those which we can, but that shouldn't cause problems elsewhere since we don't send large amounts of context data to begin with.

Pack pipelines into Sentry error reports from test mode

---

cellprofiler/gui/workspace_view/_workspace_view.py
cellprofiler/gui/workspace_view/_workspace_view_measurement_row.py

Fix #4257 
Removing measurement rows uses a different function from the other WSV artist types due to the need for multiple comboboxes. It wasn't successfully rearranging the grid when a measurements row was removed from the middle of the list (moving the subsequent items up was erroring out). I've revised this function to operate more similarly to the code used by the other artist types.

Fix removal of WSV measurement rows

---

cellprofiler/gui/app.py

The last locale fix resolved launch problems for the vast majority of machines, but there appear to be rare circumstances where Python rejects whichever locale wx passed forwards. These machines are still setting wx locale without problems, which is what caused the launch issues. Having wx and python's locale precisely matched was more of a best practice than something essential, so I've moved it into a try block which will log the problem locale name if it does error out.

Handle unsupported system locale settings

---

cellprofiler/gui/figure/_figure.py

Fixes #4260
You know how I said we don't support brightness adjustment in colour images? Now we do.
Also addressed an issue with it mistakenly treating colour images as greyscale when normalising 2D planes originating from 3D images. That should prevent it erroring out when normalisation parameters are bringing pixel values out of normal bounds.

Figure fixes for colour plots

---

cellprofiler/gui/cpframe.py
cellprofiler/gui/figure/_figure.py

The "Window" menu used to contain a list of open figure windows, but stopped working in CP4. Turns out the assigned menu label in WX4 is actually "&Window", so the previous check didn't catch it. I've just made the search for it less strict.

Fix Window menu item population on Windows

---

cellprofiler/modules/trackobjects.py

the argument names in the docstring are slightly different from the argument names in the function definition.

fix argument names in the docstring

---

cellprofiler/gui/figure/_figure.py

Fixes #4268, for the most part.
WX for some reason only has "masked" widgets for input of floats, meaning it fills unused space with empty characters. On OSX this pushes the text out of the visible area.
It was defaulting to 10 characters of space before the decimal, so I've trimmed that down to 4 (since the max allowed value is 1000). If that still doesn't fit sensibly let me know and I'll widen the entry box a bit.

Trim extra masking on Norm sliders

---

cellprofiler/modules/measureimageintensity.py
tests/modules/test_measureimageintensity.py

Resolves #4283 
I've added a setting to MeasureImageIntensity to allow the user to specify custom percentiles that they'd like to calculate. This is a bit fiddly with all the measurement generators but I think I've got it working and properly validated. Users enable the new option then enter their percentiles as a comma-separated string, e.g. "10, 20, 30" would do the 10th, 20th and 30th percentiles.
I also switched the Upper and Lower Quartile calculations over to the numpy implementation, which is much faster. Results were identical in my testing. I opted to keep these two (functionally the 25th and 75th percentiles) separate from the custom ones, partly because we want them enabled by default, but mostly because their names are pre-defined and I don't want to change what we call them …

Add custom percentile calculation to MeasureImageIntensity

---

cellprofiler/gui/module_view/_module_view.py

Alongside CellProfiler/core#60, fixes #4286
It looks like all modules which currently use `URL_FOLDER_NAME` as a directory option have an independent setting for specifying the URL of interest. They seem to ignore whatever is in the URL box provided by the directory widget, so I've removed this to reduce confusion.
CP3 appears to have had the same issue. Nonetheless since the custom path box appears to be ignored when in URL mode I think this shouldn't break anything.

Remove extra URL box from directory widget

---

cellprofiler/modules/combineobjects.py

Apparently the new module was broken as it didn't record object counts and locations properly. I'd thought that these would be deduced from the parent sets when adding a new object set, but apparently not. To fix this I've made CombineObjects be based off the Identify template and added the relevant measurement fetching functions.

Fix CombineObjects not recording object counts/positions.

---

cellprofiler/gui/module_view/_module_view.py
cellprofiler/gui/pipelinecontroller.py

Fixes #4269
Managed to fix the file selection popup, probably worth checking on OSX too. Our previous system of pulling out the file list widget from Images wasn't compatible with WX4, we now have to remove a widget from any sizers before trying to move it.
I also added a printout of any Exceptions that do occur when running this, to help flag future errors.
To test:
- Load example pipeline
- In NamesAndTypes, hit the "add a single image" button.
- Hit "browse" to select a file.
- A dialog containing the file list should appear, containing the full file list.
- Select one file and hit "OK".
- Displayed file path should update.
- Look at the Images module and make sure that the file list widget was put back correctly.
- Return to NamesAndTypes and check that the selected file was …

Fix NamesAndTypes "Add single image" functionality

---

cellprofiler/__main__.py
tests/test_main.py

Json dumping used by `--print-groups` doesnt support the np.int64 returned by Measurement.get_groupings (Issue #4294).
This pull request coerces the image numbers to Python int before generating the json file..
I wasn't sure if this could also be better fixed within the Measurement.get_groupings function. But then it might be better internally  keep image numbers consistently as np.int64.
I now also covered `print_groups` with a test.

Fix `--print-groups` by coercing np.int64 to int

---

cellprofiler/modules/exporttodatabase.py

Added a function that picks out the hostname and port number, if any, from the specified MySQL host.
Has to be in one of the following formats:
```
192.168.1.10
192.168.1.10:3306
9001:0db8:85a3:0000:0000:8a2e:0370:7334
[9001:0db8:85a3:0000:0000:8a2e:0370:7334]:3306
```

Added ability to add port number to MySQL host.

---

cellprofiler/modules/threshold.py
tests/modules/test_threshold.py
tests/resources/modules/threshold/v12.pipeline

This pull adds a new setting to Threshold (and therefore IDPrimary/Secondary) which allows the input image to be log-transformed before calculating Otsu or MCE thresholds.
In CP2 (Otsu 2-class) and CP3 (Otsu 3-class) the old Centrosome implementation of these methods was hard-coded to do this transform, but this was inconsistent with the Skimage methods. In CP4 we switched to all-Skimage implementations, but this effectively lost the old transformation functionality. It turns out that in practice the transform is very useful when you need to detect particularly weak staining in the presence of a stronger stain, usually when identifying cell boundaries.
To resolve this I've added the transform as a setting within the module. When enabled the transforms are applied before using the Skimage …

Add log normalisation option to Threshold

---

cellprofiler/modules/measurecolocalization.py

We noticed that performance of the Costes measurements in MeasureColocalization was extremely bad when working with 16-bit images. While potentially more accurate than the CP3 implementation, enabling them took module execution time from 1s to ~40s, which isn't very practical.
In this PR I've added a third mode to supplement the "Fast" mode we introduced in CP4, termed "Faster" mode. This method implements a sort-of bisection search to find the correct threshold quickly. To be precise, we progressively refine the window of possible thresholds using `min + (5/6 * width)` of the window. This prioritises the higher candidate thresholds and in practice seems to prevent us missing the target in unusual images where R value can vary wildly towards the lower threshold values.
In my testing we …

Add "Faster" Costes mode to MeasureColocalization

---

cellprofiler/modules/exporttospreadsheet.py

Fixes some bugs from #4138
- Instead of checking whether we're in headless mode, the previous version was checking for whether wx is _installed_. This caused a crash when using headless mode since wx is present, but not loaded as an app.
- Made the function aware of whether images are grouped. If so, the limit of 500 sets is considered per-group, rather than per-experiment.
- Clicking "Yes" in response to the GUI prompt will no longer skip the `check_overwrite` prompt.

Fix warning about using too many image sets with ExportToSpreadsheet.

---

cellprofiler/modules/threshold.py
tests/modules/test_threshold.py

Hopefully fixes #4312. Correction factors and bounds are now always applied after transforming back into the linear scale.
This also simplifies the individual thresholding functions somewhat.
@bethac07 Is this what you had in mind?

Untransform before correcting thresholds

---

cellprofiler/modules/graytocolor.py

Fixes #4321
Magenta and Yellow channels in GrayToColor have been swapped since at least v3.1.9. Whoops!

Correct CMYK colors

---

cellprofiler/modules/__init__.py
cellprofiler/modules/runimagejmacro.py

This is the beginning of a RunImageJMacro module in its simplest form. The way it currently works is the following:
- First, it is assumed that the macro expects a "directory" variable. This is the mechanism we chose to transfer images from CellProfiler to Fiji, and vice versa. The macro should use this "directory" variable when specifying the full path of an image to be read. It is also in this "directory" that the macro will write out images, which are then to be read by CellProfiler. The value of this variable is automatically assigned to a temporary directory created by CellProfiler.
- The user can select one or more images in the current workspace. For each of these images, the user inputs a filename expected by the macro. These image files are saved in the temporary directory …

RunImageJMacro module

---

cellprofiler/gui/pipelinecontroller.py

Fixes #4330
Turns out `\\` path separators, while valid in Python, need to be cleaned up to `\` before we pass the path to Windows Explorer. Otherwise Windows just opens the user's home directory.

Fix "Open default output folder" button in analysis complete dialog

---

cellprofiler/modules/threshold.py

Fixes #4335
By specifying a minimum 'real' difference between two pixels when calling Skimage Li we avoid the infinite loop condition that was encountered in this bug.
In my testing this fixes the problem images without changing threshold results from other cases.

Fix CP hanging when trying to run MCE thresholding on some images

---

cellprofiler/gui/omerologin.py

wxPython 4.1.0 introduces stricter checks for alignment flags, this causes the OMERO login dialog to fail:
Full error:
```
Traceback (most recent call last):
File ".../cellprofiler/gui/pipelinecontroller.py", line 3365, in do_step
self.__pipeline.run_module(module, workspace_model)
File ".../CellProfiler4.venv/lib/python3.8/site-packages/cellprofiler_core/pipeline/_pipeline.py", line 1298, in run_module
module.run(workspace)
File ".../CellProfiler4.venv/lib/python3.8/site-packages/cellprofiler_core/modules/loaddata.py", line 1092, in run
image = image_set.get_image(image_name)
File ".../CellProfiler4.venv/lib/python3.8/site-packages/cellprofiler_core/measurement/_measurements.py", line 1557, in get_image
image = matching_providers[0].provide_image(self)
File …
```

Fix OMERO login dialog for wxPython>=4.1.0

---

cellprofiler/modules/relateobjects.py

As found on the forum, a pipeline using RelateObjects with "Calculate distances to other parents" enabled has the option to add multiple object sets. When such a pipeline is loaded it will create 2 extra phantom object sets. This is because the number of object groups is determined by inspecting the length of the settings list and subtracting a constant number of fixed settings, but that number failed to include the default settings from the module's parent class. There are 7 fixed settings, not 5. Correcting this seems to stop the duplication bug.
Looks like this might have been a bug for a long time.

Fix setting duplication bug in RelateObjects

---

cellprofiler/gui/pipelinecontroller.py

Just a small fix to exporting of file lists (when the preferences option to save .txt file lists is enabled). Text files are now written with strings, so we don't need to encode URLs. Figured I'd keep in a decoding step just in case a list is passed with bytes in it.

Fix pipeline savetxt (write in str, not bytes)

---

cellprofiler/modules/correctilluminationcalculate.py

It looks like in Skimage 0.16 (so CP4) the median filter implementation was switched from the `skimage.filters.rank` method to `scipy.ndimage`. This seems to be causing problems because the ndimage implementation is substantially slower when using a large structuring element.
The two methods produce slightly different results around the borders of images due to the different handling of pixels at the edge (ndimage fills out "missing" pixels to complete the window, rank doesn't). Otherwise the results match across the rest of the image.
Considering that large window sizes are common in many workflows, I think we really need to revert to using the rank filter.
Fixes #4369

Switch CorrectIlluminationCalculate median filter back to "rank" method

---

cellprofiler/modules/combineobjects.py

One thing that's become apparent in daily use is that as image sizes and object counts grow, performance of the CombineObjects module degrades significantly.
In this PR I've revised the system for resolving non-conflicting objects (where the object in question doesn't overlap with anything in the other set). Previously we cycled through each object and added it to the output image. This was fine at a small scale, but large object sets and arrays become both time and memory intensive to run. To improve things I've made it so that we work out a list of which labels are undisputed, then copy those objects over in a single operation.
Trying this with a "heavy" pipeline (2k x 3k images) gives about an 8x speed improvement, completing an image in a few seconds rather than a minute.

CombineObjects performance optimisations

---

cellprofiler/gui/editobjectsdlg.py
cellprofiler/modules/editobjectsmanually.py

Fixes #4383
I think this is the most straightforward fix - we convert boolean images into integers, then let the default scaling parameters do the rest as normal. These images are only used for display, so there should be no consequences of changing dtype here.

Handle boolean guide images in manual object annotation modules

---

cellprofiler/__main__.py

Towards fixing #4400
The system for opening a workspace or pipeline on startup seems to work just fine, but our handling of incoming arguments was incomplete.
It sounds like at some point in time the Windows installer was set up to register an "opened with" file with a specific flag. If that's the case the setup for this is long gone, so we might as well unify Windows and MacOS handling of incoming files.
I'm going to make some revisions to the Windows installer to properly setup filetype associations. Something similar might be needed on MacOS, but I'm not sure how to approach that case.

Fix handling of pipelines/projects supplied at startup

---

cellprofiler/modules/identifysecondaryobjects.py
cellprofiler/modules/relateobjects.py
tests/modules/test_identifysecondaryobjects.py

Requires https://github.com/CellProfiler/core/pull/77 ; see also discussion in that PR.
Object processing modules it turns out were inconsistent in how their get_measurements show Children measurements to the user- some (RelateObjects (which explicitly declares its `get_measurements`) and MaskObjects (which inherits its `get_measurements` from `cellprofiler_core/module/_identify.py` returned `ChildObjName_Count`, which is indeed the actual measurement name, others that inherited from the ObjectProcessing module (`cellprofiler_core/module/image_segmentation/_object_processing`) (such as FilterObjects) returned `Count_ChildObjName`, which is wrong.  
IDSecondary explicitly did the wrong behavior, so fixing it here and in its tests; RelateObjects behavior was already correct, but here I'm …

fixes related to core #77

---

cellprofiler/modules/exporttodatabase.py
tests/modules/test_exporttodatabase.py

Fixes #3991
This PR updates the ExportToDatabase CPA properties file template for CPA 3, so generated files will now contain all the new optional parameters (set to defaults).
I've also put together a system to automatically figure out appropriate channel number and colour settings when generating a properties file for multichannel images.
This proved to be a little complicated due to the way the files are generated. The CPA properties file contents are actually generated twice for some reason, in both the pre-run and post-run phases. In the former it looks like this is sometimes logged into the database itself as the Experiment_Properties table. We have no access to image information before the run starts so that'll default to assuming 1 channel per image as before. However, during the …

Make ExportToDatabase support multichannel images when generating CPA properties files

---

cellprofiler/modules/runimagejmacro.py

Two changes in this PR:
- I've added a 'debug mode' setting which prevents CellProfiler from deleting the temporary directory used to pass data to ImageJ. This only applies in test mode and isn't saved into the pipeline at all, since otherwise you'd risk making a mess. The user needs to explicitly enable it within the module settings.
- I've made it so that CellProfiler attempts to capture and display error messages from ImageJ by attaching them to the error trace. These required some cleanup because the logs are far from tidy, but I think I have something functional:

RunImageJMacro enhancements

---

cellprofiler/modules/measureobjectsizeshape.py

A forum post asked for this, RegionProps should already be calculating this as part of the solidity measure so there should be no processing time cost.
Initially we'd avoided doing this because we generate convex hulls using Centrosome, which are then used for doing feret diameters. Skimage can't do minimum feret diameter (yet), and Centrosome's Convex Hull takes in a point list rather than an image like skimage does, so I think we'll need to keep doing both for now. With any luck we should eventually be able to drop the Centrosome element entirely.
From my testing it seems that the regionprops calculation doesn't always work in 3D, so I've only enabled this in 2D mode at the moment.

Record Convex Area in MeasureObjectSizeShape

---

cellprofiler/modules/measureobjectsizeshape.py

Fixes #4363. CP3 and earlier were in degrees and people seem to expect degrees as the unit.

Measure orientation in degrees rather than radians

---

cellprofiler/modules/graytocolor.py
cellprofiler/modules/saveimages.py

Resolves #4401 .  Requires https://github.com/CellProfiler/core/pull/80.
This allows 2-4 stacked channel images saved to be correctly saved as multichannel (vs RGB(A)) tiffs, and >4 channel tiffs to be correctly interpreted by ImageJ as multichannel rather than multistack.
Right now the only module which sets the `channelstack` property is GrayToColor, but I could definitely imagine it being useful in other modules such as the Overlay modules.

Correctly handle multichannel stacked images

---

cellprofiler/modules/filterobjects.py
tests/modules/test_filterobjects.py

Continued and rebased from #4388.
---
This PR adds a new setting to FilterObjects, "Keep removed objects", which makes the module generate an object set from any objects which were excluded by the user's defined filter.
The rationale behind this is that users often want to group objects into positive and negative groups, but in the current release a second copy of the module is needed if the user wants to carry forward a set of objects that didn't pass the filter.
At least in this version, "removed" sets aren't generated from additional sets which the user has asked the module to relabel - it's only operating on the input objects. We could add this relatively easily, but I fear it might make the settings a bit too complicated if the user has to provide two names for each group. Thoughts …

FilterObjects CPA classifier support and 'keep removed objects' option.

---

cellprofiler/gui/pipelinecontroller.py

I found an issue wherein the error dialog fails to properly display an exception message.
This primarily occurs when the input modules trigger an OSError. The handler is set up to display the EnvironmentError-specific parameter which represents the exception as a string, but this does not exist for absolutely all possible OSErrors. It defaults to None if that parameter is absent. To better handle this, I've now made it so that if that string is not defined it'll just use the default string representation of the exception, which produces a normal error message.

Fix missing exception reports in error dialog

---

cellprofiler/modules/measurecolocalization.py

A common problem has been people trying to upgrade CP3 CellPainting pipelines to CP4, then finding that MeasureColocalization is impractically slow to run. We previously used 'Accurate' mode as the default when upgrading, but since this is so slow on 16-bit images most users need to change to 'Faster' mode to use their pipelines. Having tested this more thoroughly when benchmarking CP4 and found no difference in results, I think it's safe to have 'faster' mode as the default when upgrading the module. This would save a lot of troubleshooting.

Upgrade to 'faster' Costes automatically when loading CP3 pipelines

---

cellprofiler/modules/measureobjectsizeshape.py

The calculation method was changed in CP4. While the end result is unchanged, I've clarified the description to better reflect what the measurement does.

Update Compactness measurement description

---

cellprofiler/modules/exporttodatabase.py

Turns out there's a very specific scenario where ExportToDatabase's new colour detection system fails and crashes the module. If you're in "1 table per object type" mode, without custom groups defined, and exporting all objects, the pre-run phase generates an empty objects list and therefore fails to run the image list measurement writing step.
I've added an extra call that'll ensure that write takes place if there are no objects during pre-run.

Fix ExportToDatabase CPA properties file generation

---

cellprofiler/gui/app.py
cellprofiler/gui/cpframe.py

Related to #4415, #4431, #4433
We're stuck with the current wxPython build for the time being, and that build has problems with the `wx.html2` module on Ubuntu. As a stop-gap solution I've modified the loading process to only import and construct the Welcome frame when it's requested. I've also made it so that, on machines running Linux, the 'Welcome' frame won't be automatically shown on startup. Anyone with working web extensions in their environment should still be able to use the "Help-->Show Welcome Screen" menu option.

Lazy load 'Welcome' screen, don't automatically show on Linux

---

cellprofiler/gui/pipelinecontroller.py

A consistent problem when populating the file list (at least in Windows) has been it taking a very long time to add large lists of files. If you drop a directory the result is fast because we scan subfolders with `os.walk`, but if we select the actual contents of a folder and drop 1000 files, CellProfiler would call `os.path.isfile` on every entry. On a fast local drive this isn't a massive issue, but over a network this can end up taking around 0.25s per file.
To resolve this, I've added another strategy which kicks in if the dropped file list has over 100 entries. In the new mode, we detect and call `os.scandir` on the source directory which the files came from. This produces a generator which automatically determines whether each entry is a file or folder, so we can avoid calling …

Improve file list loader performance

---

cellprofiler/modules/__init__.py
cellprofiler/modules/findmaxima.py

Particularly when working in 3D mode, generating markers for the Watershed module can be a bit painful. To address this and provide some useful functionality, I've put together a "FindMaxima" module.
It's largely a wrapper around `skimage.feature.peak_local_max`. To exclude background regions the user can specify a manual threshold, select a masking image or select a masking object set.
Output is a binary image representing peak vs non-peak pixels. I've added the customizable preview we made for IDPrimary, since the single pixels can be way too small to visualise with large images. Those options are only for the figure window and so aren't saved to the pipeline.
I can put some tests together if we think this would be a useful module to include.

Add "FindMaxima" module

---

cellprofiler/modules/threshold.py

When we added the log_transform setting to Threshold, we didn't add it to its help_settings, which meant it (and any modules that inherit threshold help_settings from it, like IPO/ISO) didn't include it in the module help.
H/T @norsimon for noticing!

Add log transform settings to module help

---

.github/workflows/release.yml
cellprofiler/__main__.py

We've still been having some issues with javabridge finding the java environment packaged into Windows builds. This should hopefully set things up correctly if the user didn't have any environment variables set at all.
I've also ported over the automatic java-finding from CPA for MacOS. Not sure if this is redundant, but it should avoid the need to manually set environment variables or have java installed elsewhere when running a build.

Improve java detection in builds

---

cellprofiler/modules/graytocolor.py

This has popped up a few times on the forum. When using SaveImages the image to export must be in float 0-1 range despite the data type supporting higher values. We recently added a rescaling function to GrayToColor that independently rescales each channel before overlay. However, when working with multiple channels in composite mode, or applying a multiplier to the image before overlay, the resulting RGB image can exceed the 0-1 range and would crash SaveImages. I had assumed that out-of-range values would be clipped when generating an image object, but apparently this only happens with values below 0.
In this PR I've added a step which clips values >1 if the user enabled rescaling. This makes the multipliers correctly "blow out" intensity with the rescaling option enabled, and ensures …

Ensure rescaled GrayToColor images remain within float range

---

cellprofiler/modules/trackobjects.py

Similar errors may still pop up elsewhere in the code, but for now this seems to get post_group running properly. The problem was that if FlagImage skipped a frame (or there were no objects??) the resulting measurements are missing from the hdf5_dict, and thus return `None` when called. In Python 2 this wasn't a problem, but in Python 3 this crashes the script when compare operations are called on the data list (NoneType can no longer be compared to ints).
Substituting 0 in these cases seems to fix it.

Fix post_group LAP crash when a frame lacks data

---

cellprofiler/gui/workspace_view/_workspace_view.py

A mild frustration I've encountered for a while has been the Workspace Viewer defaulting to red for all layers when constructing an overlay, requiring manual colour selection to change it.
I think many users will first use blue for a nuclear channel and add to that, so this PR makes the default layer colours run blue-green-red rather than red-green-blue, on the basis that blue-green is better than red-green when overlaying only 2 images.
I've also made the segmentation outline layers pull from the user's default primary, secondary and tertiary outline colours instead of red-green-blue. This should be more visually distinct from the image layers and can be easily customised by the user in the preferences dialog.

Revise workspace viewer default colors

---

cellprofiler/gui/workspace_view/_workspace_view.py
cellprofiler/modules/displaydataonimage.py
tests/modules/test_displaydataonimage.py

Fixes #4446
This PR makes it so that DisplayDataOnImage can display string measurements such as class names determined by ClassifyObjects. This allows you to make images such as this:
I've also added similar support for string measurements to the Workspace Viewer.

Support display of text-based measurements

---

cellprofiler/modules/exporttodatabase.py

- Fixed an issue where writing would fail on text columns (newly added by ClassifyObjects). SQL will try to interpret a string within a list of values as a column name, unless you enclose it in quotes.
- Fixed an issue where skipping an image or otherwise failing to capture a measurement would cause writing to fail. (`None` can't be compared in Python 3)

ExportToDatabase bug fixes

---

cellprofiler/modules/fillobjects.py
tests/modules/test_fillobjects.py

Added convex hull mode to FillObjects and added test cases for convex hull (2D and 3D).
Convex hull might be useful when processing objects that have holes that are not fully enclosed. One thing to note when using the mode is that it might create overlaps between convex hulls. Since the objects are processed sequentially, objects with higher labels will take priority to resolve this.

Add convex hull mode to FillObjects

---

cellprofiler/gui/artist.py
cellprofiler/gui/figure/_figure.py

Fixes #4453
In 4.0 we switched the workspace viewer to resizing the preview image using skimage functions instead of native MPL. Because of this the interpolation settings weren't applied and skimage defaulted to bilinear mode, which looks confusing when zoomed in.
I also found that the 'normal' figure interpolation settings didn't apply properly either, so I fixed those too. Figure windows will now also initialize with the correct default interpolation mode as determined by user preferences.

Fix interpolation functions

---

cellprofiler/data/help/other_shell.rst
cellprofiler/gui/cpframe.py
cellprofiler/gui/help/menu.py
docs/source/index.rst

This PR adds a method to access a Python interpreter within CellProfiler, aimed at helping with debugging.
To access the feature, open the 'About' dialog. Then hold `shift` while closing the About popup with the 'OK' button. This grants you the following window:
I've made it so that some useful objects are mapped into variables for easy access and inspection. All of this is using wx's inbuilt shell tool so there should be no extra dependencies.
With any luck this will allow us to more easily test packages and features within builds, too.

Add debug interpreter

---

cellprofiler/modules/measureobjectneighbors.py

Hi!
In using CellProfiler for large images (~8GB) we've found we run out of memory even on our cluster's 1.5TB nodes. The cause of the problem is in MeasureObjectNeighbors. Specifically at the point of the code modified in this PR, the original allocates 4 arrays: i, j, distance_matrix and order. Each of these arrays is of size nobjects*nneighbors. For us we have ~200000 objects. For 8 byte elements, this results in memory usage on the order of 4 * 200000 * 200000 * 8 * 10^-9 = 1280GB. But of these four arrays, the remaining code only makes use of the first three columns of order (the nearest neighbors). We have modified the code to only allocate the memory that is needed, which for the data mentioned above should not need to allocate over 1GB.
This code also runs faster than the original …

Reduce the memory usage of MeasureObjectNeighbors

---

cellprofiler/modules/saveimages.py
tests/modules/test_saveimages.py

Per a request on the forum, someone wanted to save out a label array with more than 65536 objects. ConvertObjectsToImage creates an int32 array just fine, but SaveImages' Float32 mode rescales all values to be between 0 and 1. There was no easy way to save out such an image without the rescaling. Similarly, the 8- and 16-bit modes both scale floats to integers, so you couldn't export a float image without Float32 mode's 0-1 scaling.
I've added a "No conversion" mode to the bit depth options, which tries to save the image without applying a skimage img_as_type function. I figure this gives the user a bit more flexibility in saving, with the caveat that we can't guarantee that every possible array will save properly in this mode.
While I was in there, Skimage now has a native …

Add option to disable bit depth conversion in SaveImages

---

cellprofiler/gui/figure/_figure.py

Fixes #4506
Originally, when an image is detected to have >255 objects a new matplotlib normalization is calculated up to the image.max(). However, for 3d images this leads to a new normalization to be calculated for each plane that has >255 objects and is plane specific, meaning that each plane has a different colormap applied. These changing colormaps are purely cosmetic, but can be seen in any module that uses the 3d viewer.
This fix first determines the maximum object value for an entire 3d stack. Then, it checks whether the image is 3d and if so will normalize based on the entire 3d image maximum rather than each individual plane maximum. 2d colormap generation remains unchanged.

fixed 3d cmap

---

cellprofiler/gui/figure/_figure.py

orig_image_max should only be used when a 3D image has been loaded. Prior to this fix, orig_image_max could be referenced in 2D images if the image.max() exceeded 255, resulting in an error.

Fix an error introduced in 7fd8c1c

---

cellprofiler/modules/filterobjects.py
cellprofiler/modules/measureimagequality.py
cellprofiler/modules/relateobjects.py

non-tuple multidimensional index was deprecated in numpy v1.15, and finally dropped [here](https://github.com/numpy/numpy/pull/21029). This patch addresses that, and all tests pass using numpy v1.23.1 now.
We are however still receiving a 9 or 10 warnings on numpy features that were deprecated in numpy v1.20. We should probably resolve them sooner rather than later, and we may as well on this PR.

Numpy123support

---

.github/workflows/test.yml

Right now, if any version in our matrix fails, the others are cancelled; I'd argue for letting them continue, this will allow us to pinpoint version specific issues.

Don't kill other tests if one fails

---

.github/workflows/test.yml

Pulled the trigger on merging #4595 too soon. There was a syntax error.

Fix syntax error

---

cellprofiler/gui/module_view/_module_view.py

Resolves #4382 
It looks like there were two issues here contributing to these boxes not scaling correctly. Firstly, the scaler was grabbing the names of the choices (literally "Categories" instead of the actual categories, etc). Secondly, it didn't know what the choices were, because they hadn't yet been populated. By grabbing them earlier, we can populate all the possible options (hence combining images and objects) when we do the sizing, allowing the boxes to be properly scaled. 
We should check that this doesn't break anything on Windows, of course.

Use correct scaler, populate choices

---

cellprofiler/gui/figure/_figure.py
cellprofiler/modules/resize.py

The changes to imshow_color also mean that having >3 channels in a volumetric image won't break the display.
Resolves #4567

Use imshow_color in Resize

---

cellprofiler/modules/exporttospreadsheet.py
tests/modules/test_exporttospreadsheet.py

Resolves #4467 
If the user skips an image, and that image is not either the first or the last image (hence the weird behavior the user was seeing about needing all 3 images), ExportToSpreadsheet was unhappy because the object count for that image was NaN. Before we only checked if it was missing, I'm not sure if ie FlagImage's behavior changed or something deeper in the stack, but it's worth checking for both. I've also added a test for this condition.

Handle skipped images in object-containing spreadsheets

---

cellprofiler/modules/splitormergeobjects.py
tests/modules/test_splitormergeobjects.py

Resolves #4586 
CellProfiler objects didn't use to be require being consecutively numbered, but now they do. SplitOrMergeObjects, when unifying objects per-parent, still just gave the parent's number, which made labels sometimes non-consecutive if parents didn't have any children. This (which is basically copied wholesale from #3799) fixes that.

Force per-parent labels to be consecutive

---

cellprofiler/modules/exporttospreadsheet.py

Resolves #4548 
So this was a corner case - the user had used the "Select the measurements to export" setting to only select object features for one class (no image features at all were selected), but GCTs require a couple specific Image features for the file to get created (and you would in general want to export them all!). I've added a check so that it doesn't actively error if the user hasn't selected the right things, but also a validation error to tell the user what they need to do in order for this to work.

Make sure required columns for GCTs are exported

---

cellprofiler/__main__.py
cellprofiler/gui/preferences_dialog/_preferences_dialog.py

Requires https://github.com/CellProfiler/core/pull/105
Resolves #4486 , Resolves #4527 
The change to `__main__` allows you to do this when executing the pipeline headlessly (by passing `--always-continue`) as a flag in your execution command; the change to the preferences menu allows a user running in GUI to set this preference.

Allow users to run without stopping for errors in GUI and headless mode.

---

cellprofiler/__main__.py
cellprofiler/data/help/other_batch.rst

Requires https://github.com/CellProfiler/core/pull/107. Resolves #4413 .
The old function relied on a lot of very shaky logic, mostly because the function it was used to check grouping might report either grouping OR just metadata, and CellProfiler will cry if you try to pass it `g` groups without grouping being on in the pipeline. It also in general preferred to give out `-f -l` switches even if `-g` was possible, which feels to me harder to understand what is going on, and more of a pain if you need to rerun just some groups. 
I think we should just use this new one in CP5, but it's arguably a breaking change so we can "deprecate" and hold off.

New way to make batch commands

---

cellprofiler/modules/savecroppedobjects.py
tests/modules/test_savecroppedobjects.py

Added the option to add input filenames to output crops and also the possibility to save output crops into nested folders.

Added additional save features to SaveCroppedObjects

---

cellprofiler/gui/cpframe.py
cellprofiler/gui/imagesetctrl.py

Companion PR to CellProfiler/core#119
This will display series names in the plane details view (if present). SeriesName field will appear in brackets as below:
This is using zarrs with a custom reader, but the same should result from any reader which supports the new parameter.
While I was in there I also fixed the path list in MacOS dark mode and fixed a drag-drop bug.

Display SeriesName in Images file list (imagesetctrl)

---

cellprofiler/gui/pathlist.py
cellprofiler/gui/pipelinecontroller.py

An issue that's come up in testing is that it's not trivial to add URLs to the file list in the Images module. I believe the current best method is via loading a text file.
This PR should make it so that the user can instead directly paste a list of URLs (or file paths) into the file list in the Images module, and have them be treated as if you'd just drag-dropped.

Allow pasting of files into the file list

---

cellprofiler/gui/pathlist.py
cellprofiler/gui/pipelinecontroller.py
cellprofiler/gui/utilities/figure.py

In the Images module you can double-click on an image in the file list to attempt to preview it.
Since this module can now display a list of series within an image file, I've made it so that you can double click an entry in the series list to preview that specific series (instead of it always showing the first).
I've also made the display engine normalise the preview data so as to be consistent with how CellProfiler will display the images elsewhere in the UI.

Support previewing a series in the Images module

---

cellprofiler/modules/erodeobjects.py
cellprofiler/utilities/morphology.py

`ErodeObjects` module feels particularly slow when there are many objects in the mask.  The current implementation is a for-loop on each object coupled with an erosion applied on the whole mask. Consequently, there is a lot of redundancy. 
It is actually possible to replace this for-loop/erosion implementation by a single morphological operation. The morphological gradient (i.e. dilate - erosion) captures the contour of individual connected components, with a width and shape dependent on the kernel size and shape. It is possible to get the eroded objects by setting to 0 the contour pixels of the original mask.
There is a second improvement in the midpoints preservation algorithm. When the kernel is "Disk,1", the midpoint of a removed object is the original objects itself. In this trivial …

Improve ErodeObjects performance

---

cellprofiler/__main__.py
cellprofiler/gui/cpframe.py
cellprofiler/gui/pipelinecontroller.py
cellprofiler/gui/preferences_dialog/_preferences_dialog.py
cellprofiler/gui/readers_dialog/_readers_dialog.py

Requires CellProfiler/core#126
This PR adds a 'Configure Readers' option to the File... menu, allowing users to customise image reader setup. The primary goal here is to give more control over the modular readers. This will also apply to readers loaded as plugins.
Readers are divided into Active and Inactive groups. Active readers are those available for use by CellProfiler, Inactive readers are those that are either disabled by the user or failed to load properly. Displaying broken readers should ease debugging of plugins.
Every reader now has an Enable/Disable toggle. Readers can also define their own custom settings.
Example panel for a functional reader:
Example panel for a reader that failed to initialize:
I've also added an 'Export' button to the original Preferences dialog, which …

Add reader configuration GUI

---

cellprofiler/__main__.py

Requires CellProfiler/core#130, invokes ~`fill_readers()`~ `activate_readers(check_config=True)` **after** headless mode is determined. This is especially important when running tests (which use headless mode) in github actions since the `get_config()` function in CellProfiler/core/cellprofiler_core/preferences/__init__.py will import `wx` if it does not detect headless mode, and therefore cause the tests to exit prematurely because a framework build of python is required.

Fill readers

---

tests/modules/test_saveimages.py

According to https://numpy.org/doc/stable/reference/arrays.scalars.html#numpy.int64, numpy.int64 can have many different aliases. This can lead to test failures on some platforms (Windows).
However, numpy.int_ appears to consistent with the expected results for test_save_image_tiff_int32

Update test_save_image_tiff_int32 expected data type

---

cellprofiler/library/functions/object_processing.py
cellprofiler/library/modules/__init__.py
cellprofiler/library/modules/_fillobjects.py
cellprofiler/modules/fillobjects.py

Adding FillObjects to the library. This one works in a way that is slightly different to the other modules added so far due to `FillObjects` class inheriting from the `ObjectProcessing`. Basically, the library function needs to be passed as a lambda function to the `self.function` attribute and allows us to keep everything that `ObjectProcessing` does.

Adding FillObjects to library

---

setup.py

Changes introduced in #4741 require skimage>=0.19, otherwise tests fail

bump skimage to 0.19

---

cellprofiler/modules/expandorshrinkobjects.py

@callum-jpg and I were code-reviewing various library modules yesterday and he pointed out that this first one was in a much less ideal state than some of the later ones, in that essentially in the module-module we were handling a lot of the logic (in terms of which parameters need to be passed to the sub functions and which do not) that is [already handled in the library-module](https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/library/modules/_expandorshrinkobjects.py#L4-L17). This PR cleans that up; I think the fact that now the mappings between settings and library functions are now more explicit is a particularly nice bonus!

Simplify ExpandorShrinkObjects logic

---

cellprofiler/library/functions/image_processing.py
tests/modules/test_threshold.py

Library incorrectly assumed the dimension order was xyz, rather than zxy for volumetric images. This PR fixes that.
Also added a new test for oblong volumetric images, since all of the previous volumetric tests are cubes.

Fix library threshold dimension order for volumetric images

---

tests/modules/test_measureimageoverlap.py

sk-learn has broken the same 2 tests 3 times across different versions, so loosen constraint to be within 1% of expected value

Loosen earth movers assertion

---

.github/workflows/release.yml

It can be nice to see if even if one OS build is failing, if the other succeeds; we can always cancel a run we want to stop if we do actually want it to stop.

Change fail-fast to false on builds

---

cellprofiler/modules/exporttodatabase.py

Resolves #4690 
The previous way ExportToDatabase tried to get access to the channel names worked in the GUI but failed headlessly. I extracted the creation of that list to a function, so that if we don't have it pre-calculated in places where we need it, it's simple to run it.

Fix property file access to channel names in headless runs

---

cellprofiler/modules/exporttospreadsheet.py

Resolves #4653 
ExportToSpreadsheet gets mad trying to say "what is the biggest number objects that I have in this image" if there are object creation modules that are skipped.

Catch "no objects of any type"

---

cellprofiler/gui/addmoduleframe.py
cellprofiler/utilities/rules.py
setup.py

Module search uses exact substring matching, which is a bit too strict. We'd like to allow for spelling mistakes and skipping characters but still display sensible results ranked according to closest match.
For instance when searching for "IdentifyTertiaryObjects"
typing: `"zidentifytertiaryobjects"` should still work even with the leading `"z"` character
likewise typing `"idtertiary"` should work, where you type the leading `"id"`, skip over `"entify"`, followed by `"tertiary"`
This PR uses Damerau-Levenshtein distance similarity for fuzzy search. There's **a lot** of other choices, and a whole research field in this subject (eg driven by sequence alignment in genomics) as well as a bunch of custom open source solutions used in various tools (eg `fzf` or VSCode's file search). I was not …

Make module search fuzzy

---

cellprofiler/knime_bridge.py

In file: knime_bridge.py, the list named `__all__` contains undefined names which can result in errors when this module is imported. The module name should be of string type. I created a string for the module name. For more information regarding `__all__`, please read about [importing fields from a package](https://docs.python.org/3/tutorial/modules.html#importing-from-a-package).  
Here is a [video](https://drive.google.com/file/d/1nOyQuHKcrDVAkIitdZS4O3g5hZLw6jV7/view?usp=sharing) that demonstrates the type error that happens during import when the module name is not represented as a string. Here when `foo` is exported, it is not done as a string. So, when this is imported and used, we get an error.
Sponsorship and Support:
This work is done by the security researchers from …

Update a module name to allow import without type errors

---

cellprofiler/gui/cpframe.py
cellprofiler/gui/plugins_menu.py

This PR adds a container which plugins can place custom menu entries into during loading. If entries were added, a new "Plugins" menu will appear in the main menubar (after "Test").
This is intended to allow plugin authors to add extra functionality to the GUI. For example with the OMERO reader we'll have a menu entry to let the user open up the server connection dialog.

Add plugin menu

---

distribution/docker/Dockerfile

ubuntu 18 does not come with python 3.9 and has reached EOL, update dockerfile to use ubuntu 20
credit to @wheelern
resolves #4864

Bump dockefile for python 3.9

---

src/frontend/cellprofiler/modules/measureimageoverlap.py
src/subpackages/library/cellprofiler_library/functions/measurement.py

Resolves #4890 
TLDR, we reshape the image to make the measurement easier, and then we never put it back.

Enable 3D display in MeasureImageOverlap

---

cellprofiler/modules/runimagejmacro.py

May, or may not, resolve #4858 . It only happened in 4.2.6 built, so possibly we need not do anything, but this seems safe enough. Did not happen in 5 built, so no companion PR.

Add error catching to subprocess for RunImageJMacro

---

cellprofiler/modules/threshold.py

@gnodar01 , this is the least-messy way I could think of to do that (because stuff like `unique` has weird behavior with nan's present, but `nan`'s also evaluate to true, so...), but if you can think of something more elegant and performant (likely), let me know and I'm happy to switch the implementation. Will hold off making a PR to main until we decide how to efficiently implement.

Catch case where in local thresholding, image is mixture of nan and 0

---

.github/workflows/test.yml
pixi.lock
pixi.toml
src/subpackages/core/cellprofiler_core/analysis/_runner.py
src/subpackages/core/cellprofiler_core/utilities/zmq/_boundary.py
tests/core/analysis/test_analysis.py

Addresses #4859 (maybe). Logging statements were added throughout in order to track the source of the error. Most logging statements, within individual tests, did nothing to alter the sporadic failures. However, after putting logging statements within the `__exit__` method of `FakeWorker`, several dozen runs of testing did not run into the error.
This may have been coincidence. For instance, It could be the case, that although the macos version is specified, different VMs provided by GitHub cause the error to occur, or not occur. Given that the multiple successful runs were conducted over a period of three days (mostly during the weekend), there may have been a string of lucky VM allocations.
However, if the simple act of logging within `__exit__` did indeed fix the problem, it points to …

Core Tests

---

pixi.lock
src/frontend/pyproject.toml
src/subpackages/core/cellprofiler_core/analysis/_runner.py
src/subpackages/core/cellprofiler_core/constants/worker.py
src/subpackages/core/cellprofiler_core/measurement/_measurements.py
src/subpackages/core/cellprofiler_core/utilities/zmq/__init__.py
src/subpackages/core/cellprofiler_core/utilities/zmq/_boundary.py
src/subpackages/core/cellprofiler_core/utilities/zmq/_event.py
src/subpackages/core/cellprofiler_core/worker/_worker.py
src/subpackages/core/pyproject.toml

The problem:
From a debug log of running CP on a pipeline which encounters the issue of a hanging post-processing step, we have this as our final Progress before the hang:
```
[CP - DEBUG] cellprofiler_core.analysis._runner::interface: 👺 sending Progress - [(89, 'FinishedWaitingMeasurements'), (90, 'FinishedWaitingMeasurements'), (92, 'FinishedWaitingMeasurements'), (93, 'FinishedWaitingMeasurements'), (95, 'FinishedWaitingMeasurements'), (96, 'FinishedWaitingMeasurements'), (97, 'FinishedWaitingMeasurements'), (99, 'FinishedWaitingMeasurements'), (101, 'FinishedWaitingMeasurements')]
[CP - INFO] cellprofiler.gui.pipelinecontroller::analysis_event_handler: Progress, Counter({'Done': 231, 'FinishedWaitingMeasurements': 9})
```
I ran the pipeline on `240` image sets, so it wasn't the last …

Fix worker halting

---

src/frontend/cellprofiler/modules/measureobjectneighbors.py

Added sharexy argument for neighbors plot that was not zooming-in in sync with other outputs
Resolves #4988 and #4628

Fix issue #4988 : MeasureObjectNeighbors visualization zooming

---

src/frontend/cellprofiler/modules/filterobjects.py
tests/frontend/modules/test_filterobjects.py

As discussed with @bethac07 last week, the #4509 issue bug occurs when there is a mismatch in the labels assigned to the object being filtered and the `Additional Object`s that the user wishes to relabel. A decision was made to add a note in the docs, clarifying that the user needs to `RelateObjects` prior to using this module to ensure that the labels assigned to the newly created object sets match the labels of the object being filtered. 
We chose this option instead of automatically relabeling the `Additional Object` in order to avoid redundant functionality among modules.

FilterObjects relabel mismatch Issues/4509
