CellProfiler/CellProfiler

- cellprofiler/gui/cpframe.py
- cellprofiler/gui/pipelinecontroller.py
- cellprofiler/pipeline.py
- cellprofiler/tests/test_pipeline.py
@0x00B1 here's a pull request for issue #1417. Review and merge?
> fixes #1417 + tests

- external_dependencies.py
Reverts CellProfiler/CellProfiler#1503
> Revert "Did not find ij1-patcher.jar (fixes #1500)"

- external_dependencies.py
Reverts CellProfiler/CellProfiler#1498
> Revert "Decompress prokaryote-*.*.*.tar.gz"

- CellProfiler.py
- cellprofiler/utilities/cpjvm.py
- external_dependencies.py
- setup.py
- windows_setup.py
Reverts CellProfiler/CellProfiler#1484
> Revert "Retrieve prokaryote-*.*.*.jar during setup"

- cellprofiler/gui/cpfigure.py
- cellprofiler/gui/pipelinelistview.py
This branch has several related fixes for figure window display. #1595, #1596 and #1599
> Fixes for WX figure window issues

- cellprofiler/modules/run_imagej.py
@0x00B1 I removed the imports and I think it will work but somehow my Maven stuff has gone off the deep end and so I can't run the run_imagej tests.
If you check out this branch and it works, I'm glad I could help, but no guarantees.
> Removed missing import, but it remains untested

- cellprofiler/gui/cpfigure.py
- cellprofiler/gui/pipelinelistview.py
> Fixes #1606 - centralize finding figure window in cpfigure.find_fig and fix for wx 3.0

- cellprofiler/modules/metadata.py
Don't bother messing with the metadata joiner if the user turned metadata matching off
> Fixes #1530

- cellprofiler/modules/calculatestatistics.py
- cellprofiler/modules/tests/test_calculatestatistics.py
Subdirectory is created if it doesn't exist to match the style of SaveImages
> Fixes #1478 - create subdirectory for figure files + tests

- CellProfiler.py
- cellprofiler/modules/createbatchfiles.py
- cellprofiler/modules/tests/test_createbatchfiles.py
@dlogan has a work-around for this. The bug has a description of the solution in it. It also should fix issue #1397
> Fixes #1518 - write default image/output dir to experiment meas + tests

- cellprofiler/cpmath/__init__.py
- cellprofiler/cpmath/tests/__init__.py
Conflicts:
cellprofiler/cpmath/__init__.py
cellprofiler/cpmath/bg_compensate.py
cellprofiler/cpmath/cpmorphology.py
cellprofiler/cpmath/filter.py
cellprofiler/cpmath/haralick.py
cellprofiler/cpmath/index.py
cellprofiler/cpmath/lapjv.py
cellprofiler/cpmath/otsu.py
cellprofiler/cpmath/outline.py
cellprofiler/cpmath/princomp.py
cellprofiler/cpmath/propagate.py
cellprofiler/cpmath/radial_power_spectrum.py
cellprofiler/cpmath/rankorder.py
cellprofiler/cpmath/smooth.py
cellprofiler/cpmath/tests/__init__.py
cellprofiler/cpmath/threshold.py
cellprofiler/cpmath/watershed.py
cellprofiler/cpmath/zernike.py
> Fixes #1627: Guild the lilly until it sinks

- cellprofiler/modules/makeprojection.py
Checked the build on Travis - the error message is now gone.
> Fixes #1570 explicitly take real part of complex conjugate

- cellprofiler/modules/classifyobjects.py
- cellprofiler/modules/tests/test_classifyobjects.py
Old and unnecessary code was operating incorrectly.
> Fixes #1636 + test

- .travis.yml
Much of this copied from features/py2exe
> Change .travis.yml to make the build pass

- cellprofiler/modules/reassignobjectnumbers.py
- cellprofiler/modules/tests/test_reassignobjectnumbers.py
@braymp let me know if this works for your real data, merge if OK.
> Fixes #1789 - don't mask children by parents / use parent measurement

- cellprofiler/__main__.py
- cellprofiler/cellprofilerapp.py
- cellprofiler/gui/cpframe.py
> removed splash screen

- cellprofiler/modules/exporttodatabase.py
@braymp Mark, one last for you to look at. Forgot to do this and it was on the bug list. LMK if it needs adjusting.
:heart: Lee
> Fixes #1776 - fields for tracer in props file

- .travis.yml
- cellprofiler/modules/tests/test_calculatemath.py
Trying to see why build is breaking first, then will fix.
> Fix a problem with a binary skimage wheel on pypi

- .travis.yml
- cellprofiler/modules/tests/test_exporttodatabase.py
Fixes #1814
.travis.yml is configured to use a MySQL database.
> Fixes #1814 test_exporttodatabase - can configure MySQL database

- cellprofiler/__main__.py
no -b switch in CellProfiler command-line
> Fixes #1894

- cellprofiler/gui/regexp_editor.py
This  parses the Phenix format, but the WellRow is still numeric and Well will not be what you expect until #1677 is fixed by upgrading prokaryote.
> Fixes #1824 - added parser for Phenix format

- cellprofiler/modules/plugins/imagetemplate.py
Resolves https://github.com/CellProfiler/CellProfiler/issues/2150
/cc @0x00B1
> [2150] Add figure parameter to display method in ImageTemplate.

- setup.cfg
> Remove cellprofiler.matlab from setup.cfg

- cellprofiler/__main__.py
> put back -t/--temporary directory option.

- cellprofiler/gui/viewworkspace.py
- cellprofiler/image.py
- cellprofiler/modules/correctilluminationcalculate.py
- cellprofiler/modules/crop.py
- cellprofiler/modules/exporttocellh5.py
- cellprofiler/modules/filterobjects.py
- cellprofiler/modules/loaddata.py
- cellprofiler/modules/makeprojection.py
- cellprofiler/modules/tile.py
- tests/modules/test_correctilluminationcalculate.py
- tests/modules/test_expandorshrinkobjects.py
- tests/modules/test_loaddata.py
- tests/modules/test_loadimages.py
- tests/test_image.py
> Refactor properties in cellprofiler.image

- cellprofiler/object.py
> Remove memoization

- cellprofiler/gui/editobjectsdlg.py
- cellprofiler/modules/identify.py
- cellprofiler/modules/plugins/measurementtemplate.py
- cellprofiler/object.py
- tests/test_objects.py
> Refactor properties in cellprofiler.object

- cellprofiler/gui/moduleview.py
- cellprofiler/setting.py
> Create setting cellprofiler.setting.StructuringElement

- cellprofiler/image.py
- tests/test_image.py
> Represent a volume as an image

- cellprofiler/gui/figure.py
> Visualize a volume

- cellprofiler/modules/dilation.py
- cellprofiler/modules/erosion.py
Quick one for review @0x00b1 
(Can you adjust your editor to trim trailing whitespace, please?)
> Display images side by side.

- cellprofiler/modules/saveimages.py
> Re-expose option for alternate colormaps

- cellprofiler/modules/gammacorrection.py
Documentation updates and visible settings corrections for GammaCorrection.
@0x00b1
> Gamma correction

- cellprofiler/image.py
- cellprofiler/modules/convertobjectstoimage.py
- cellprofiler/object.py
- tests/modules/test_convertobjectstoimage.py
- tests/test_objects.py
> Volumetric support for ConvertObjectsToImage

- CONTRIBUTING.md
@AnneCarpenter @0x00b1 Thoughts?
> Add guidelines for contributing to CellProfiler.

- cellprofiler/modules/namesandtypes.py
- tests/modules/test_namesandtypes.py
> Add volumetric option to assignments

- cellprofiler/modules/edgedetection.py
> Add dimensions to workspace.display_data

- cellprofiler/modules/activecontourmodel.py
- cellprofiler/modules/randomwalkeralgorithm.py
- cellprofiler/modules/watershed.py
> Set parent_image on segmentations

- cellprofiler/image.py
- cellprofiler/measurement.py
- tests/modules/test_measureimageintensity.py
- tests/test_image.py
> Volumetric support for MeasureImageIntensity

- cellprofiler/gui/figure.py
> Use consistent intensity scale for volume display.

- tests/modules/test_measureimageintensity.py
Update existing tests to use pytest fixtures.
> MeasureImageIntensity test updates

- setup.py
> Exclude pyamg 3.2.0

- cellprofiler/gui/figure.py
> Linearly scale values close to 0

- cellprofiler/modules/watershed.py
- tests/modules/test_watershed.py
> Improve watershed running time by downsampling large volumes

- LICENSE
- cellprofiler/gui/dialog.py
> It's 2017.

- cellprofiler/modules/__init__.py
Updates #2042 with latest master and updates class name in error message to match current class name.
> Raise ValueError

- cellprofiler/modules/identifyprimaryobjects.py
- tests/modules/test_identifyprimaryobjects.py
* documentation formatting
* cleaner HTML
* use formatting and explicit variables
* optimize imports and remove import aliases
* PEP08 compliance
Next: IPO should support volumes :)
> Clean IdentifyPrimaryObjects formatting

- cellprofiler/modules/thresholding.py
- tests/modules/test_thresholding.py
* skimage returns integer result, not boolean
* result is data >= threshold value
resolves #2568
> fix local thresholding with otsu and percentile

- cellprofiler/modules/histogramequalization.py
- tests/modules/test_histogramequalization.py
> add local option to histogram equaliztion

- cellprofiler/gui/pipelinecontroller.py
- cellprofiler/modules/identify.py
> remove reference to removed function

- cellprofiler/modules/identify.py
- cellprofiler/modules/identifyprimaryobjects.py
- tests/modules/test_identifyprimaryobjects.py
- tests/test_knime_bridge.py
> Add advanced settings toggle to IdentifyPrimaryObjects (resolves #2577)

- cellprofiler/modules/maskimage.py
@mcquin did all the hard work.
> MaskImage should support volumes (resolves #2605)

- cellprofiler/modules/gaussianfilter.py
- cellprofiler/modules/histogramequalization.py
- tests/modules/test_histogramequalization.py
It is now possible to specify the kernel size when using the local setting of HistogramEqualization.
> Histogram equalization kernel

- cellprofiler/modules/relateobjects.py
- tests/modules/test_relateobjects.py
* Clean documentation formatting
* Remove `% globals`, be explicit
* Remove import aliases
* Optimize imports, remove duplicate imports
* PEP08 compliance
> Clean formatting for RelateObjects

- cellprofiler/modules/expandorshrinkobjects.py
- tests/modules/test_expandorshrinkobjects.py
* clean docs
* pep08 compliance
* remove import aliases
* optimize imports
> Clean formatting for ExpandOrShrinkObjects

- cellprofiler/module.py
Don't use **np** as an alias for **numpy**. It is rude.
> change np to numpy (resolves #2657)

- cellprofiler/module.py
- cellprofiler/modules/activecontourmodel.py
- cellprofiler/modules/randomwalkeralgorithm.py
- cellprofiler/modules/watershed.py
- tests/modules/test_randomwalkeralgorithm.py
- tests/modules/test_watershed.py
- tests/test_module.py
Record object measurements for objects identified in Image Segmentation modules.
> Record object measurements (resolves #2653)

- cellprofiler/gui/artist.py
Implements Mark's solution from that issue.
> Change inplace operation (resolves #2156)

- cellprofiler/modules/measuregranularity.py
> Volumetric support for MeasureGranularity

- cellprofiler/modules/measureimagequality.py
> Volumetric support for MeasureImageQuality

- cellprofiler/gui/pipelinecontroller.py
> Add error message to dialog. Print stack trace to logger. (Resolves #2691)

- cellprofiler/modules/filterobjects.py
> Remove image underlay in display (resolves #2719)

- cellprofiler/gui/pipelinecontroller.py
File > Save Project As... dialog to default to the directory where the
project is from
> File > Save Project As... default directory

- cellprofiler/modules/gammacorrection.py
> Use "Gamma" in setting text.

- cellprofiler/image.py
- cellprofiler/modules/enhanceorsuppressfeatures.py
- cellprofiler/modules/gaussianfilter.py
- tests/modules/test_loadimages.py
- tests/modules/test_namesandtypes.py
- tests/test_image.py
> Return normalized image spacing

- cellprofiler/__main__.py
> relative paths with -i

- cellprofiler/pipeline.py
> fixed version mismatch message

- cellprofiler/modules/metadata.py
clicking on update button in metadata shows how many rows were found
(similar to NamesAndTypes)
> update button in metadata gives feedback

- cellprofiler/modules/measurecorrelation.py
- tests/modules/test_measurecorrelation.py
Resolves #2680 
Could one of @braymp or @apahl please verify this fix?
> Use an inclusive threshold to capture 0 values.

- cellprofiler/__main__.py
> Recursively search --image-directory

- cellprofiler/gui/editobjectsdlg.py
Fixing incorrect initialization of CanvasPatch object.
Solves https://github.com/CellProfiler/CellProfiler/issues/2443
> Fix #2443 EditObjectsDialog

- cellprofiler/modules/measurecorrelation.py
- tests/modules/test_measurecorrelation.py
> Compute features when data is available

- cellprofiler/modules/morph.py
NB: I've no way to check that I've not messed up formatting since I don't have source installed 😨
> Clarify help about image padding, resolves #1669

- cellprofiler/modules/colortogray.py
For rationale, see [RFC](https://github.com/CellProfiler/RFC/pull/2)
> Adds more channels to the display of Split mode in ColorToGray

- cellprofiler/modules/measureimageareaoccupied.py
- tests/modules/test_measureimageareaoccupied.py
* Remove import aliases and optimize imports
* Use str.format
* Remove '% globals'
* PEP08 compliance
> Formatting changes for MeasureImageAreaOccupied

- cellprofiler/modules/measureimageareaoccupied.py
- tests/modules/test_measureimageareaoccupied.py
Compute volumetric measurements for MeasureImageAreaOccupied.
> Volumetric support for MeasureImageAreaOccupied. Resolves #2460.

- cellprofiler/modules/measuretexture.py
- tests/modules/test_measuretexture.py
* remove %globals
* use str.format
* pep08
* optimize imports and remove import aliases
> MeasureTexture formatting

- cellprofiler/modules/identifyprimaryobjects.py
* Set default hole filling to after thresholding only.
* Only discard excess objects in advanced mode and LIMIT_ERASE is selected.
Resolves #2817 #2818 #2819 
/cc @karhohs
> Advance mode defaults and basic mode behave the same.

- cellprofiler/modules/measuretexture.py
- tests/modules/test_measuretexture.py
> Volumetric support for MeasureTexture

- cellprofiler/gui/app.py
- cellprofiler/gui/dialog.py
- cellprofiler/preferences.py
> Prompt for telemetry once.

- cellprofiler/modules/tophattransform.py
> Save top hat transformation operation.

- cellprofiler/module.py
- cellprofiler/modules/identifysecondaryobjects.py
> Fix help search.

- cellprofiler/modules/saveimages.py
- tests/modules/test_saveimages.py
> save images as 32-bit floating point

- CellProfiler.spec
- setup.py
Use:
```sh
pyinstaller.exe CellProfiler.spec
cp C:\Python27\Lib\site-packages\zmq\libzmq.pyd .\dist\CellProfiler\
```
> PyInstaller (Windows)

- cellprofiler/modules/measureobjectsizeshape.py
> Explain directionality of orientation.

- cellprofiler/gui/addmoduleframe.py
> Remove "Where's my module?" button

- cellprofiler/modules/saveimages.py
> Convert 8 to 8-bit integer, 16 to 16-bit integer.

- cellprofiler/modules/closing.py
- cellprofiler/modules/dilation.py
- cellprofiler/modules/erosion.py
- cellprofiler/modules/gaussianfilter.py
- cellprofiler/modules/label.py
- cellprofiler/modules/medialaxis.py
- cellprofiler/modules/medianfilter.py
- cellprofiler/modules/morphologicalskeleton.py
- cellprofiler/modules/opening.py
- cellprofiler/modules/removeholes.py
- cellprofiler/modules/removeobjectsbysize.py
- cellprofiler/modules/watershed.py
> Modules moved to Advanced category

- cellprofiler/module.py
> Renaming 'Input' and 'Output' in module.py to "Select the input image" and "Name the output image" respectively

- cellprofiler/modules/calculatemath.py
> Edit documentation CalculateMath

- cellprofiler/modules/clearborder.py
> Moved ClearBorder to Advanced

- cellprofiler/modules/threshold.py
I merged Threshold too soon. Taking care of Beth's requests and some extra formatting.
> Minor documentation fixes

- cellprofiler/gui/cpframe.py
> Fix printing and saving help

- cellprofiler/modules/identifyprimaryobjects.py
Whoo, that one was a bear!  There's some new documentation on 2D vs 3D and on the advanced settings that @AnneCarpenter may want to check out.
> Documentation identifyprimaryobjects

- cellprofiler/modules/watershed.py
- tests/modules/test_watershed.py
> optional downsampling

- cellprofiler/gui/help/content.py
Not sure if this will conflict w Claire's refactoring, and I can't test in-GUI because I'm editing in the browser vs from source. I am worried about newline/line endings. Sorry!
> Documentation - Why Use CellProfiler menu item in content.py

- cellprofiler/modules/convertobjectstoimage.py
- cellprofiler/modules/crop.py
- cellprofiler/modules/expandorshrinkobjects.py
- cellprofiler/modules/exporttospreadsheet.py
- cellprofiler/modules/identifyprimaryobjects.py
- cellprofiler/modules/makeprojection.py
- cellprofiler/modules/maskimage.py
- cellprofiler/modules/maskobjects.py
- cellprofiler/modules/measurecolocalization.py
- cellprofiler/modules/measuretexture.py
- cellprofiler/modules/overlayoutlines.py
- cellprofiler/modules/rescaleintensity.py
- cellprofiler/modules/trackobjects.py
Build updated documentation cleanly.
> Documentation fixes

- cellprofiler/module.py
- cellprofiler/modules/loaddata.py
> Change the output message when naming images/data in module.py

- cellprofiler/modules/convertobjectstoimage.py
@mcquin can you please check my updated descriptions for grey and uint to see if they're still accurate?  I tried to make them more parallel but am afraid there may be some nuance I haven't grasped.
> ConvertObjectsToImage docfixes

- cellprofiler/modules/morphologicalskeleton.py
- cellprofiler/modules/removeholes.py
> Applied CamelCase to RemoveHoles and MorphologicalSkeleton

- cellprofiler/gui/help/content.py
> Clarify Default Input Folder help content

- cellprofiler/modules/saveimages.py
fix formatting for module help
> fix formatting

- cellprofiler/pipeline.py
> Initalize pipeline as 3D when a 3D pipeline is loaded.

- cellprofiler/modules/identifyprimaryobjects.py
Someone please check accuracy of my new lines 48-50?
> Documentation - IdentifyPrimaryObjects

- cellprofiler/modules/groups.py
- cellprofiler/modules/identifyprimaryobjects.py
- cellprofiler/modules/identifysecondaryobjects.py
- cellprofiler/modules/images.py
- cellprofiler/modules/measureobjectsizeshape.py
- cellprofiler/modules/metadata.py
- cellprofiler/modules/namesandtypes.py
- cellprofiler/modules/trackobjects.py
Resolves #3065
I've verified on my machine that after pulling #3070 images should embed nicely in both GUI and sphinx
> Fix image embeddings in module top docs

- cellprofiler/gui/figure.py
- cellprofiler/module.py
- cellprofiler/modules/convertobjectstoimage.py
- cellprofiler/modules/crop.py
- cellprofiler/modules/filterobjects.py
- cellprofiler/modules/imagemath.py
- cellprofiler/modules/maskimage.py
- cellprofiler/modules/matchtemplate.py
- cellprofiler/modules/measureimageskeleton.py
- cellprofiler/modules/measureobjectneighbors.py
- cellprofiler/modules/overlayoutlines.py
- cellprofiler/modules/relateobjects.py
- cellprofiler/modules/resize.py
- cellprofiler/modules/threshold.py
This doesn't solve #2496 but it does restore linked zooming on 2D displays in affected modules (essentially, modules with 3D support).
> Reactive zoom on 2D image display.

- cellprofiler/modules/resize.py
- tests/modules/test_resize.py
> Round dimensions when rescaling by factor.

- cellprofiler/gui/help/content.py
Resolves #3022 and contributes towards #2840, among others
> Docfix helpcontent

- cellprofiler/gui/help/content.py
LoadImages and LoadSingleImages are still considered deprecated.
> Undeprecate LoadData.

- cellprofiler/modules/threshold.py
> Documentation - Adaptive thresholding in threshold.py

- cellprofiler/modules/measureimagequality.py
Please note that I want to make two more changes: moving the m'ment descirptions and references. but due to potential for messing formatting, best to do those separately once this harmless PR is merged.
> Documentation - MeasureImageQuality

- cellprofiler/modules/measureimagequality.py
Moved the references and descriptions of metrics to the Measurements made section.
Important: someone please look at this in a GUI. I really hope I didn't mess up links and formatting but please fix it up if you can.
> Documentation - Measure Image Quality

- cellprofiler/modules/measureimageintensity.py
reconciling help text with MeasureObjectIntensity
> Documentation - MeasureImageIntensity

- cellprofiler/modules/exporttospreadsheet.py
> Documentation - ExportToSpreadsheet

- cellprofiler/modules/saveimages.py
The metadata fixes solve #3151
The masking fixes solve #3152
I'm flying blind here so please check the results in the GUI (esp the part about metadata!)
> Documentation - SaveImages

- cellprofiler/modules/measureobjectsizeshape.py
Some help please:
1) Please someone verify line 71 where I added centroid - is it true? And/or, can anyone elaborate on why it's different than LocationX from Identify?
2) see change max to min in line 102, correct?
> Documentation - MeasureObjectSizeShape

- cellprofiler/modules/identifyprimaryobjects.py
> Disable declumping settings when "None" is selected.

- cellprofiler/modules/_help.py
- cellprofiler/modules/loadimages.py
reStructuredText is unhappy when including a list in a list. 
Let's avoid doing that.
> Fix reST formatting in LoadImages

- cellprofiler/modules/savecroppedobjects.py
Using the term "mask" is confusing. Get specific about what this module generates.
> Clarify documentation

- cellprofiler/modules/identifydeadworms.py
- cellprofiler/modules/straightenworms.py
- cellprofiler/modules/untangleworms.py
Resolves #3142 
Worm modules should all live together happily under the "Worm Toolbox" category.
> Worm modules category is Worm Toolbox.

- cellprofiler/modules/relateobjects.py
I moved "Distances" to be a child measurement rather than a parent one, please confirm that's accurate.
> Documentation - RelateObjects

- cellprofiler/modules/identifysecondaryobjects.py
> Deleting "what do the settings mean"

- cellprofiler/modules/identifyprimaryobjects.py
> Deleted "what do the settings mean?"

- cellprofiler/modules/smooth.py
Adding reference to related Advanced modules
> Documentation - Smooth

- cellprofiler/modules/measureimageareaoccupied.py
- tests/modules/test_measureimageareaoccupied.py
> Remove option to save a binary image.

- cellprofiler/modules/measureobjectintensitydistribution.py
Note that in the interface the question "Calculate intensity Zernikes?" is cutoff and appears as just  "Calculate intensity". I don't know how to fix that.
> Documentation - MeasureObjectIntensityDistribution

- cellprofiler/modules/exporttodatabase.py
1) Can someone add a prefix to "At the secure shell" - the question I had here was "why are you telling me to do this?" Should the prefix be something like "Once you have completed the pipeline containing **ExportToDatabase** you will be ready to load (launch?) the database as follows:"
2) Please confirm my warning about the password is correct? (line ~731)
> Documentation - ExportToDatabase (part 1)

- cellprofiler/modules/imagemath.py
> Documentation - explain that ImageMath inverts entire image and mask

- cellprofiler/modules/exporttospreadsheet.py
Solves #1110
I'm flying blind so I've no idea if I rendered the URL properly. Please check it in the GUI!
> Documentation - ExportToSpreadsheet DOF behavior

- cellprofiler/modules/splitormergeobjects.py
- tests/modules/test_splitormergeobjects.py
See: https://github.com/CellProfiler/CellProfiler/pull/3241
> Unify --> Merge

- cellprofiler/modules/displaydensityplot.py
This one ALMOST squeaked by w no changes from me!
> Documentation - DisplayDensityPlot

- cellprofiler/gui/figure.py
Resolves #2021 
2D display (grayscale):
2D display (multichannel):
3D display (grayscale):
3D display (multichannel)
> Display intensity statistics

- cellprofiler/modules/identifysecondaryobjects.py
> Updated docstring for fill_holes

- cellprofiler/modules/measureimageskeleton.py
> updated MeasureImageSkeleton docstring

- cellprofiler/modules/tile.py
> Documentation - Tile

- cellprofiler/modules/calculatestatistics.py
I don't know why there is a vertical line at line 28, before "**LoadData** loads information fr..."
Possibly try to delete it and see what happens?
> Documentation - CalculateStatistics

- cellprofiler/modules/filterobjects.py
> updated classifier docs

- cellprofiler/modules/smooth.py
Smooth is to be consistent with CorrectIlluminationCalculate, which share smoothing algorithms. #3194
> update smooth module for consistency

- cellprofiler/modules/namesandtypes.py
Resolves #3298
Note that I changed the intro help to indicate YES for "Supports 3D?": I can't think of any good reason it would've been set otherwise.
> Settings/help edits for NamesAndTypes

- cellprofiler/modules/metadata.py
I've already done NamesAndTypes. 
I know it's a little weird to say that these Input modules support 3D because in some cases that is sort of irrelevant to the function of the module but whatever, it's better than people thinking they are NOT 3D compatible (if left as NO) or that we forgot to make a notation for the module (if we took out the table altogether).
> Documentation - Input modules are 3D compatible, 3

- cellprofiler/modules/measureimageareaoccupied.py
- tests/modules/test_measureimageareaoccupied.py
> Sum up objects, fix 3D assertion

- cellprofiler/gui/app.py
> Sentry should not send INFO or DEBUG messages

- cellprofiler/modules/savecroppedobjects.py
- tests/modules/test_savecroppedobjects.py
> Create output subdirectories in SaveCroppedObjects

- cellprofiler/modules/removeholes.py
- tests/modules/test_removeholes.py
Additionally, added some simple documentation.
> Only convert floating point data to binary.

- cellprofiler/modules/watershed.py
> Update Watershed Documentation

- cellprofiler/modules/morph.py
- tests/modules/test_morph.py
Resolves #3349 
Load a pipeline with Morph without failing fast when encountering
an operation which has been moved to a separate module. Also
includes a tip on how to upgrade your pipeline.
> Load Morph without error.

- cellprofiler/gui/welcome.py
> Add In-App Help text to welcome screen

- cellprofiler/gui/help/content.py
- cellprofiler/gui/help/menu.py
- cellprofiler/gui/welcome.py
> Update links to the new manual.

- cellprofiler/modules/morph.py
- tests/modules/test_morph.py
> Remove "life" option from Morph

- cellprofiler/gui/figure.py
> Fix for colormap access in DisplayPlatemap

- cellprofiler/data/help/other_batch.rst
- cellprofiler/data/help/output_measurements.rst
Second PR that addresses #3180 (which can be closed after both of these are merged).
> Help RST typos

- cellprofiler/gui/addmoduleframe.py
> Make reST render as HTML in Add Module window

- cellprofiler/data/help/other_multiple_pipelines.rst
- cellprofiler/gui/runmultiplepipelinesdialog.py
> Run Multiple Pipelines help now displays properly

- cellprofiler/gui/cpframe.py
Resolves #3404 
Only took me two hours to figure out this one line fix :smile:
> Fix "Help for module #" not displaying module help

- cellprofiler/gui/editobjectsdlg.py
> Manual split will no longer attempt to restore the region to "None"

- cellprofiler/modules/tile.py
> Re-arrange Tile help settings to correspond with settings order

- LICENSE
- cellprofiler/gui/dialog.py
- docs/source/modules/license.rst
Resolves #3442 
Happy New Year.
> Increment copyright year.

- cellprofiler/gui/figure.py
> Force navtoolbar to have minimum height of 40

- cellprofiler/gui/moduleview.py
- cellprofiler/modules/exporttodatabase.py
> All moduleview option text should be right-aligned

- cellprofiler/gui/figure.py
> Skip normalization on images with 0-length dimension.

- cellprofiler/modules/plugins/imagetemplate.py
- cellprofiler/modules/plugins/measurementtemplate.py
Resolves #2289 
A high-level overview of the changes made to templates:
- PEP 08/consistent formatting
- Remove import aliases and use absolute imports
- Include sections and section description in top-level module documentation
- Ensure templates are functional (i.e., they can be run as plugins)
> Update module templates to reflect current style

- cellprofiler/gui/moduleview.py
> Ensure a settings refresh doesn't occur while one is in progress

- cellprofiler/data/help/projects_image_sequences.rst
- cellprofiler/gui/help/content.py
Resolves #3234 
This is a rebase of #3272.
> Update documentation for loading image stacks

- cellprofiler/modules/enhanceorsuppressfeatures.py
Minor bug found by @melissahendershott 
Resolves #3472
> Fix mask existence check

- cellprofiler/modules/metadata.py
> Check the reserved tags without case sensitivity

- cellprofiler/modules/imagemath.py
- tests/modules/test_imagemath.py
> Use numpy.logical_xor to subtract binary images in ImageMath

- cellprofiler/gui/help/content.py
- cellprofiler/modules/_help.py
- cellprofiler/modules/groups.py
- cellprofiler/modules/identifyprimaryobjects.py
- cellprofiler/modules/images.py
- cellprofiler/modules/measureobjectintensitydistribution.py
- cellprofiler/modules/measureobjectsizeshape.py
- cellprofiler/modules/metadata.py
- cellprofiler/modules/namesandtypes.py
- cellprofiler/preferences.py
> Fix image resource paths

- cellprofiler/gui/html/htmlwindow.py
> support for https:// links in GUI help

- .gitignore
- cellprofiler/gui/moduleview.py
- cellprofiler/modules/metadata.py
- cellprofiler/setting.py
- tests/modules/test_metadata.py
> Allow location of metadata CSVs in default IO folders

- cellprofiler/modules/calculatemath.py
> Add explicit volumetric support to CalculateMath

- cellprofiler/modules/measureobjectsizeshape.py
Use FilterObjects' border mode to remove objects touching the edge of the image.
> Remove reference to ClearBorder, use FilterObjects.

- cellprofiler/gui/pipelinecontroller.py
- cellprofiler/misc.py
- cellprofiler/modules/exporttodatabase.py
- cellprofiler/modules/exporttospreadsheet.py
- cellprofiler/modules/images.py
- cellprofiler/modules/loaddata.py
- cellprofiler/modules/loadimages.py
- cellprofiler/modules/loadsingleimage.py
- cellprofiler/modules/metadata.py
- cellprofiler/modules/namesandtypes.py
- cellprofiler/pipeline.py
- cellprofiler/preferences.py
- setup.py
- tests/modules/test_createbatchfiles.py
- tests/modules/test_exporttodatabase.py
- tests/modules/test_exporttospreadsheet.py
- tests/modules/test_images.py
- tests/modules/test_loaddata.py
- tests/modules/test_loadimages.py
- tests/modules/test_namesandtypes.py
Resolves #3507
✅ Requires https://github.com/CellProfiler/python-bioformats/pull/98
✅ Requires https://github.com/CellProfiler/prokaryote/pull/41
> Support s3

- cellprofiler/gui/pipelinecontroller.py
- cellprofiler/modules/saveimages.py
Import category constants from measurements
> Fix imports

- cellprofiler/modules/watershed.py
- tests/modules/test_watershed.py
I also reformatted some of the docstrings.
> Add additional parameters to skimage seeded watershed

- cellprofiler/modules/relateobjects.py
- tests/modules/test_relateobjects.py
Resolves the long-awaited #249
> Issues/249 - Add mapped/labeled objects as output of RelateObjects

- cellprofiler/modules/convertimagetoobjects.py
Previously, a pre-labeled array would be relabeled, which might give objects new numbers. This could be undesirable if measurements were made on the previous object numbers, so I've added an option to allow those original labels to be preserved.
I also added in some requested parameters for the relabeling, specifically connectivity and background label.
> Add ability to preserve labels and parameters for labeling

- cellprofiler/modules/watershed.py
- tests/modules/test_watershed.py
Realized I forgot a settings revision...so here it is! 
Also, mahotas and skimage consider "connectivity" differently, so I've changed the variable names to reflect that and make it a little less confusing.
> Add settings revision for watershed and rename parameters for clarity

- cellprofiler/object.py
> PEP 8 Refactor and moved functions around for better clarity

- cellprofiler/modules/watershed.py
Dumb fix for a settings revision I added - this makes it so that if you're reloading the pipeline it still works!
> Pass default settings along if nothing changed

- cellprofiler/modules/displaydataonimage.py
- cellprofiler/modules/measureobjectneighbors.py
- cellprofiler/object.py
- tests/modules/test_identifytertiaryobjects.py
I believe this is a viable fix for #3541 - I've tested it with the pipeline/data supplied and it seems to display the data appropriately!
> Appropriately handle differences in object numbers and objects available

- .travis.yml
- setup.py
It looks like the `cache` key was missing in the YAML and this caused some parse issues in Travis CI - hope this helps!
> Fix caching section for Travis CI

- setup.py
> h5py now really no longer pinned below 2.8

- cellprofiler/gui/pipelinecontroller.py
> Don't display a correctly saved file list dialog when one isn't saved

- cellprofiler/modules/colortogray.py
> Use image name values

- requirements.txt
- setup.py
- unpinned_requirements.txt
Bump bioformats/javabridge versions
> #3648 Bump python-bioformats version

- unpinned_requirements.txt
Reverts CellProfiler/CellProfiler#3664
> Revert "Set numpy to be higher than the travis default (1.13)"

- cellprofiler/modules/savecroppedobjects.py
- tests/modules/test_savecroppedobjects.py
Resolves #2255 
Taking the best of @SariNusier 's PR #2831  and putting it on top of the current expanded functionalities of SaveCroppedObjects.
> SaveCroppedObjects, redux

- cellprofiler/modules/createbatchfiles.py
> Explicitly make CreateBatchFiles volumetric

- cellprofiler/__main__.py
This wraps most of the processing in a `try...finally` which will attempt to close the JVM if something goes wrong. 
This is best viewed by checking "Hide whitespace changes".
> #3656 Stop the JVM if errors are encountered during headless startup

- cellprofiler/modules/identifysecondaryobjects.py
Resolves #3613 
Resolves #3614
> use objectname.value

- setup.py
> Pin pytest to <4 until tests are fixed

- requirements.txt
> Bump numpy version to 1.15.4

- cellprofiler/modules/filterobjects.py
> Make FilterObjects respect masks

- tests/modules/test_convertboolimagetoobjects.py
- tests/modules/test_convertimagetoobjects.py
- tests/modules/test_convertlabeledimagetoobjects.py
- tests/modules/test_convertobjectstoimage.py
- tests/modules/test_measureimageskeleton.py
I have updated the code according to recommendations in the pytest 4 documentation. Test are now able to run again. This fixes #3688.
> Upgrade tests to be compatible with pytest 4

- cellprofiler/utilities/hdf5_dict.py
- cellprofiler/utilities/zmqrequest.py
removed python2 code
@0x00b1 @bethac07
> unresolved reference since no python 2 buffer() in python 3

- cellprofiler/gui/pipelinecontroller.py
- cellprofiler/pipeline.py
@0x00b1 @AetherUnbound @bethac07
> WIP: read in text mode instead of binary mode

- cellprofiler/gui/html/htmlwindow.py
- cellprofiler/gui/pipelinecontroller.py
- cellprofiler/gui/pipelinelistview.py
- cellprofiler/measurement.py
- cellprofiler/modules/correctilluminationapply.py
- cellprofiler/modules/identifyprimaryobjects.py
- cellprofiler/modules/identifysecondaryobjects.py
- cellprofiler/modules/overlayoutlines.py
- cellprofiler/modules/relateobjects.py
- cellprofiler/pipeline.py
- cellprofiler/utilities/hdf5_dict.py
@0x00b1 @bethac07 @AetherUnbound 
hey all, i understand that i had reincorporated some of the en/decode stuff but unless we remove the \x__ sequences in the example cppipe, i don't think it's possible to load it. Please let me know if i'm missing anything.
-JS
Update: I've also tested loading the pipelines in repo https://github.com/CellProfiler/examples
> Python3 load example cppipe continuation

- cellprofiler/gui/pathlist.py
- cellprofiler/gui/pipelinecontroller.py
@0x00b1 @bethac07 @AetherUnbound
> Image Loading

- cellprofiler/gui/help/content.py
- cellprofiler/gui/pipelinelistview.py
- cellprofiler/preferences.py
@0x00b1 @bethac07 @AetherUnbound 
For Issue https://github.com/CellProfiler/CellProfiler/issues/3779
Written on top of PR https://github.com/CellProfiler/CellProfiler/pull/3790
> Python3 issue 3779

- cellprofiler/gui/help/content.py
- cellprofiler/gui/imagesetctrl.py
- cellprofiler/preferences.py
@0x00b1 @bethac07 @AetherUnbound 
For Issue https://github.com/CellProfiler/CellProfiler/issues/3781
Also added on top of PR https://github.com/CellProfiler/CellProfiler/pull/3790
> Python3 issue 3781

- cellprofiler/gui/help/content.py
- cellprofiler/gui/moduleview.py
- cellprofiler/gui/regexp_editor.py
- cellprofiler/preferences.py
@0x00b1 @bethac07 @AetherUnbound 
For Issue https://github.com/CellProfiler/CellProfiler/issues/3783
this PR is also built on top of PR https://github.com/CellProfiler/CellProfiler/pull/3790
> Python3 issue 3783

- cellprofiler/gui/help/content.py
- cellprofiler/gui/imagesetctrl.py
- cellprofiler/gui/moduleview.py
- cellprofiler/gui/pipelinelistview.py
- cellprofiler/gui/preferencesview.py
- cellprofiler/gui/regexp_editor.py
- cellprofiler/measurement.py
- cellprofiler/pipeline.py
- cellprofiler/preferences.py
- cellprofiler/utilities/hdf5_dict.py
- cellprofiler/utilities/legacy.py
- cellprofiler/workspace.py
@bethac07 @0x00b1 @AetherUnbound 
For Issue https://github.com/CellProfiler/CellProfiler/issues/3784
Fix is ugly on this one so please let me know if a better idea comes to mind.
Btw, this PR doesn't yet fix the whole CP 3.1.8 cpproj loading bug, just the one addressed in the ticket. The problem remaining is to load the images from the cpproj file.
Added on top of PR https://github.com/CellProfiler/CellProfiler/pull/3790
> Python3 issue 3784

- cellprofiler/modules/loadimages.py
- tests/modules/test_correctilluminationcalculate.py
> test_correctilluminationcalculate

- cellprofiler/modules/loadsingleimage.py
- cellprofiler/pipeline.py
- tests/modules/__init__.py
- tests/modules/test_createbatchfiles.py
- tests/modules/test_loadimages.py
- tests/modules/test_loadsingleimage.py
had to modify pipeline.load() again to match tests
tested on ubuntu and windows for cppipe versions 3, 4, and 5
> test_createbatchfiles

- cellprofiler/modules/exporttodatabase.py
- tests/modules/test_exporttodatabase.py
will need help testing the majority of them since i'm getting a
`_mysql_exceptions.OperationalError: (2005, "Unknown MySQL server host 'imgdb02.broadinstitute.org' (2)")` error
> Test_exporttodatabase

- tests/modules/test_measureobjectintensity.py
// and removed fixture annotation
helper function instead
> test_measureobjectintensity

- cellprofiler/modules/measureimagequality.py
- tests/modules/test_measureimagequality.py
> test_measureimagequality

- cellprofiler/gui/tools.py
- cellprofiler/modules/exporttodatabase.py
- tests/modules/test_definegrid.py
fixed matplotlib error using BytesIO; although matplotlib 3.1.0 documentation mentions it taking a str, it is actually bytes
removed matlab v1 test and others
> Matplotlib requires fd in bytes for tests

- cellprofiler/modules/identifysecondaryobjects.py
> Don't allow hole filling to expand into existing objects

- cellprofiler/gui/figure.py
> Handle object counts >255

- cellprofiler/data/help/other_plugins.rst
- cellprofiler/gui/cpframe.py
- cellprofiler/gui/figure.py
- cellprofiler/gui/imagesetctrl.py
- cellprofiler/gui/pathlist.py
- cellprofiler/gui/pipelinecontroller.py
- cellprofiler/gui/pipelinelistview.py
- cellprofiler/modules/imagemath.py
- cellprofiler/modules/morphologicalskeleton.py
Have been working through the spreadsheet of issues found during the previous round of CP4 testing.
> Fix WX4 GUI bugs

- cellprofiler/gui/editobjectsdlg.py
- cellprofiler/gui/pipelinecontroller.py
- setup.py
Been working on a few more issues from the spreadsheet
> A couple more CP4 fixes

- cellprofiler/modules/convertobjectstoimage.py
- cellprofiler/modules/measureobjectneighbors.py
- tests/modules/test_measureobjectneighbors.py
> Fix MeasureObjectNeighbors with two object sets

- cellprofiler/module.py
- cellprofiler/modules/expandorshrinkobjects.py
- cellprofiler/modules/identifytertiaryobjects.py
- cellprofiler/modules/maskobjects.py
> WIP - Give object adjustment panels a shared colormap

- cellprofiler/gui/figure.py
Turns out this was broken in CP4.
> Fix 3d mode figure window display

- cellprofiler/modules/exporttodatabase.py
- cellprofiler/modules/exporttospreadsheet.py
> Fix documentation for Export modules- they respect masks and work in 3D

- cellprofiler/gui/figure.py
- cellprofiler/modules/calculatemath.py
- cellprofiler/modules/measurecolocalization.py
- cellprofiler/modules/measuregranularity.py
- cellprofiler/modules/measureobjectintensity.py
- cellprofiler/modules/measureobjectintensitydistribution.py
- cellprofiler/modules/measureobjectsizeshape.py
- cellprofiler/modules/measuretexture.py
Added optional header text for tables. Closes #1373.
> For measurement modules that display a chart, make clear the fact that an aggregate is shown 

- cellprofiler/gui/pipelinelistview.py
> Fix scrollbars on pipeline list viewer

- cellprofiler/gui/regexp_editor.py
> Fix regex error handling

- cellprofiler/modules/classifyobjects.py
> Fix ClassifyObjects with paired measurements

- cellprofiler/modules/imagemath.py
Fixes #3947. User can now tell ImageMath to replace nan with 0.
> Add NaN substitution to ImageMath

- cellprofiler/modules/resizeobjects.py
- tests/modules/test_resizeobjects.py
Closes #3948.
Adding a third mode didn't play well with the lambda functions, so I've replaced that. Also added some tests for this.
> Add option to resize to an image's dimensions to ResizeObjects

- cellprofiler/gui/pipelinecontroller.py
> Add confirmation when aborting an analysis run

- cellprofiler/gui/pipelinecontroller.py
- cellprofiler/measurement.py
- cellprofiler/modules/flagimage.py
- cellprofiler/modules/groups.py
- cellprofiler/modules/loaddata.py
- cellprofiler/modules/saveimages.py
- cellprofiler/pipeline.py
- tests/modules/test_exporttospreadsheet.py
- tests/modules/test_groups.py
- tests/modules/test_loadimages.py
- tests/test_pipeline.py
Resolves some lingering issues from #310
> Allow user to bypass skipping the last image of a cycle

- cellprofiler/__main__.py
Resolves #3340, Resolves #3341
> Download pipelines or CSVs from URL

- cellprofiler/modules/tile.py
> Use image_name.value

- cellprofiler/preferences.py
> Make default colour preferences colourblind-friendly

- cellprofiler/gui/preferencesdlg.py
> Remove IJPluginDirectory setting

- cellprofiler/modules/relateobjects.py
Resolves #3692 (for real this time)
> Fix missing .value in RelateObjects

- cellprofiler/gui/figure.py
Fixes #4035.
Previously subplots wouldn't update when changing the display mode of specific object sets. To clean things up I've moved the figure refreshing process into a dedicated function which cuts down on some repetition elsewhere as well.
With regards to the overlay transparency slider, dragging the slider in this dialog was set up to try to automatically refresh the subplot, but this didn't actually work and had miserable performance even after I'd tried improving it. As a result I've just made it refresh the plot once the user hits 'OK', I don't think this functionality was used much anyway since it's been broken since at least CP3.
> Make subplots refresh properly when settings are updated

- cellprofiler/gui/pipeline.py
Seems like exporting a pipeline didn't actually work (project file saving was ok). This hopefully should get it working.
> Fix exporting of cppipe pipeline files

- cellprofiler/gui/cpframe.py
- cellprofiler/gui/pipelinecontroller.py
- cellprofiler/gui/plateviewer.py
Resolves #4040
Some basic wx upgrade problems, I've made more elements expand to fill empty space since wx4 seems to be bad at sizing empty tables/fields.
This function is very particular about the metadata formatting it will accept. We might want to re-think or expand on the documentation for this in the future, but for now I've added better exception handling to inform the user when something is wrong (rather than the window just not opening).
> Fix plate viewer

- cellprofiler/modules/convertobjectstoimage.py
- cellprofiler/modules/untangleworms.py
Closes #3311. I've already updated NamesAndTypes within CPCore.
> Update documentation on overlapping objects

- cellprofiler/gui/regexp_editor.py
> Add new regex guess for INCell

- cellprofiler/modules/exporttodatabase.py
This mode apparently doesn't work too well and is almost entirely replicated by ExportToSpreadsheet.
Resolves  #2961, Closes #2820
> Remove MySQL/CSV mode from ExportToDatabase

- cellprofiler/modules/enhanceorsuppressfeatures.py
- tests/modules/test_enhanceorsuppressfeatures.py
> Make EnhanceOrSuppressFeatures neurite rescaling optional

- cellprofiler/modules/watershed.py
Updated watershed documentation
> Updated Watershed documentation

- cellprofiler/modules/closing.py
- cellprofiler/modules/dilateimage.py
- cellprofiler/modules/erosion.py
- cellprofiler/modules/opening.py
Updated the links in Erosion, Closing, Opening and DilateImage modules help.
> LinkUpdate

- cellprofiler/data/help/other_3d_identify.rst
- cellprofiler/gui/help/menu.py
- cellprofiler/gui/help/search.py
- docs/source/index.rst
Resolves #2561. Thanks to @NasimJ!
We might want to make a link to this doc in the IDPrimary module?
> Add docs on how to replicate Identify modules in 3D.

- cellprofiler/data/examples/ExampleFly/ExampleFly.cppipe
> better example pipeline settings

- cellprofiler/modules/correctilluminationapply.py
User now has the option to clip values to ensure values are between 0 and 1.
> clipping intensities in illumination function

- cellprofiler/modules/measurecolocalization.py
> Colocalization documentation

- docs/source/modules/measurement.rst
> Add MeasureObjectOverlap to manual

- cellprofiler/modules/measurecolocalization.py
> Improve validation for MeasureColocalization

- cellprofiler/__main__.py
> Fix packaged analysis workers

- cellprofiler/gui/cpframe.py
> added now Windows menu for showing/hiding windows

- cellprofiler/gui/cpframe.py
- cellprofiler/gui/help/menu.py
> Add 'About' option to help menu

- cellprofiler/modules/correctilluminationapply.py
- tests/modules/test_correctilluminationapply.py
> Optionally clip output 0-1

- cellprofiler/modules/untangleworms.py
Function was removed from matplotlib.mlab in matplotlib 3.
> Replace mlab.prctile with numpy.percentile

- cellprofiler/modules/exporttospreadsheet.py
Previously we were trying to decode strings. We now check whether we have bytes before trying to decode.
> decoding only if incoming bytes

- cellprofiler/modules/measuretexture.py
- tests/modules/test_measuretexture.py
> Fix scale reporting in MeasureTexture

- cellprofiler/modules/rescaleintensity.py
Fix #4243
RescaleIntensity will now default to using the 0-1 range if the user provides an image which is entirely masked off.
Also cut down on some unnecessary repetition of image masking.
> Make RescaleIntensity handle fully masked arrays

- cellprofiler/gui/pipelinecontroller.py
Derp.
Requires cellprofiler/core#54
> Fix and enable pipeline sanitization

- cellprofiler/modules/exporttodatabase.py
> fixes issue 4254

- cellprofiler/modules/exporttodatabase.py
- tests/modules/test_exporttodatabase.py
That will help make sure Sentry isn't collecting data we don't want collected.
> make all references to passwords use that word specifically

- .github/workflows/release.yml
Resolves the other half of #4250
> Edit Info.plist during release process

- tests/modules/test_trackobjects.py
it should be 7 according to the following description.
> possible typo

- cellprofiler/data/help/projects_introduction.rst
added explicit mention of .cppipe
> Docs update

- cellprofiler/gui/figure/_figure.py
Turns out the 3D viewer was still mistakenly thinking greyscale images are color. I need to do further testing with this, but I believe this PR will still be an improvement that gets us most of the way there.
> Improve colour image detection

- cellprofiler/__main__.py
- cellprofiler/gui/pipelinecontroller.py
- cellprofiler/gui/preferences_dialog/_preferences_dialog.py
Interface for new setting, requires  cellprofiler/core#65
> Add 'conserve memory' setting

- cellprofiler/modules/identifysecondaryobjects.py
- tests/modules/test_identifysecondaryobjects.py
> Fix renumbering of secondary objects after filtering

- cellprofiler/modules/identifyprimaryobjects.py
Resolves #4430
This PR adds an option to IdentifyPrimaryObjects to change the size of the markers used to display local maxima.
I've also removed the maxima display settings (on/off, colour and size) from the pipeline. These settings are visual options and only apply to the figure display, so we might as well keep complexity down and not persist them between sessions.
Sizing works based on customising the radius of a disk structuring element, which is then used to dilate the maxima. If you want big red maxima markers, that's now possible:
> Configurable local maxima marker size

- cellprofiler/gui/pipelinecontroller.py
Required by CellProfiler/core#89
> Move JSON handling to cp core

- cellprofiler/modules/exporttodatabase.py
Added Z coordinates and 3D flag to exporttodatabase for use with CPA with 3D datasets.
> Added Z coordinates and 3D flag to exporttodatabase

- cellprofiler/modules/measureimageareaoccupied.py
- cellprofiler/modules/measureobjectsizeshape.py
> Updated marching_cubes function name

- cellprofiler/modules/displaydataonimage.py
Added additional options to DisplayDataOnImage, as requested by #4529. Though the requested features for multiplication of a value or removing 0's to the left of the `.` were not added.
> Display data on image enhancement

- cellprofiler/modules/saveimages.py
Changes SaveImages.py to have more documentation about how to set up and use the Base image folder option when saving images with subfolders.
> Added more information about saving images in subfolders

- cellprofiler/modules/measureimagequality.py
Resolves #4424 , tests passing
Co-authored-by: lmanubens
> Fix grid range in 3D

- cellprofiler/modules/resize.py
- cellprofiler/modules/resizeobjects.py
- tests/modules/test_resize.py
> Fix broken upgrade_settings in Resize and ResizeObjects

- cellprofiler/data/help/projects_image_ordering.rst
- cellprofiler/gui/help/menu.py
- docs/source/index.rst
> Add image ordering info to documentation

- cellprofiler/gui/figure/_figure.py
> Force z planes to stay in range

- cellprofiler/modules/expandorshrinkobjects.py
- tests/modules/test_expandorshrinkobjects.py
> Updating ExpandOrShrink with additional measurement feature to cellprofiler.library

- cellprofiler/modules/exporttospreadsheet.py
> Only run GCT validation check if making a GCT

- cellprofiler/__main__.py
- cellprofiler/data/help/navigation_test_menu.rst
- cellprofiler/data/help/other_widget_inspector.rst
- cellprofiler/gui/cpframe.py
- cellprofiler/gui/help/menu.py
- cellprofiler/gui/preferences_dialog/_preferences_dialog.py
- docs/source/index.rst
- add option to set widget_inspector, enabling it as item under "Test" menu
- needs corresponding core changes, in CellProfiler/core#111
> Add widget_inspector option

- cellprofiler/modules/exporttodatabase.py
- cellprofiler/modules/measureobjectskeleton.py
- tests/modules/test_filterobjects.py
The goal of this PR is to make the code more Pythonic by utilizing Python `with` statements.
> [Refactoring] making the code more Pythonic

- cellprofiler/modules/measuregranularity.py
> fix subsample values >1 overwriting input image

- cellprofiler/__init__.py
- tests/test_cellprofiler.py
Run the version check unit test on all platforms so that it runs on CI.
Also fix the version string so this test passes.
> Version check all platforms

- cellprofiler/gui/readers_dialog/_readers_dialog.py
Companion to CellProfiler/core#131. Displays supported schemes in Configure Readers dialog.
> Display supported schemes in configure readers

- cellprofiler/modules/exporttodatabase.py
> Patch headless creation of properties files

- cellprofiler/modules/straightenworms.py
Complement to CellProfiler/core#140
> Remove deprecated numpy aliases

- cellprofiler/gui/imagesetctrl.py
- cellprofiler/gui/module_view/_module_view.py
- cellprofiler/gui/pathlist.py
- cellprofiler/gui/pipelinecontroller.py
- cellprofiler/gui/utilities/module_view.py
- cellprofiler/modules/createbatchfiles.py
- cellprofiler/modules/straightenworms.py
PR addressing #4693, but also other general pipeline refactoring work.
Companion to PR CellProfiler/core#139.
Note that this builds off, and will be merged into, the not yet merged scyjava branch.
> Update metadata conventions

- cellprofiler/modules/enhanceorsuppressfeatures.py
- cellprofiler/modules/findmaxima.py
- cellprofiler/modules/identifyprimaryobjects.py
- cellprofiler/modules/measuregranularity.py
- cellprofiler/modules/reducenoise.py
- cellprofiler/modules/smooth.py
- tests/modules/test_closing.py
- tests/modules/test_dilateimage.py
- tests/modules/test_dilateobjects.py
- tests/modules/test_erodeimage.py
- tests/modules/test_erodeobjects.py
- tests/modules/test_measuregranularity.py
- tests/modules/test_opening.py
- tests/modules/test_reducenoise.py
- tests/modules/test_smooth.py
- tests/modules/test_watershed.py
> Support skimage 0.20

- cellprofiler/modules/correctilluminationcalculate.py
minor docs fix: fix two external links
> fix tutorial/example links in docs

- cellprofiler/gui/cpframe.py
- cellprofiler/gui/pipelinecontroller.py
- cellprofiler/modules/makeprojection.py
- cellprofiler/modules/plugins/imagetemplate.py
- cellprofiler/modules/plugins/measurementtemplate.py
- cellprofiler/modules/runimagejmacro.py
Follow-up on creating a citation generator from [this pull request](https://github.com/CellProfiler/CellProfiler/pull/4744), based on Rebecca and Barbara's work.
> Citation generator vs2

- cellprofiler/modules/watershed.py
@bethac07 This is an outstanding commit that was going to be included in `library-watershed`, but since that's already been pulled I just created a new PR instead. Only `upgrade_settings` has any important changes, in the 3 -> 4 condition, the rest is just tidying.
> Create revision path for new watershed module

- cellprofiler/modules/flagimage.py
> Support 3D images in FlagImage

- cellprofiler/modules/measureimageareaoccupied.py
Companion to #4726 , if we decide there not to handle all 4 cases, just one, change that here too.
> Don't check perimeter when area is 0

- cellprofiler/modules/unmixcolors.py
I haven't fully tested this out yet (hence draft), and I think the case it's covering is mostly a corner case, but AFAICT, there's no reason we shouldn't be able to support UnmixColors being 3D by running it planewise.
> Add ability to run planewise to UnmixColors

- cellprofiler/modules/exporttodatabase.py
Seems in addition to the other fix mentioned in #4805, it also fixes the issue #4695 solved. I've rebased this on master and also reverted the changes made there.
> Replace measurement-based ExportToDB state transmission with shared_state implementation

- .github/workflows/test.yml
- pytest.ini
As yet unsolved, but attempts to fix #4859
> Fix core tests

- .github/workflows/nightly.yml
> Remove testpypi ref

- src/frontend/pyproject.toml
- src/subpackages/core/pyproject.toml
- src/subpackages/library/pyproject.toml
centrosome v1.2.3 fixes broken build in CellProfiler/centrosome/pull/124
> Bump Centrosome to working build

- .gitignore
- flake.lock
- flake.nix
- nix/cellprofiler.nix
- nix/cellprofiler_core.nix
- nix/cellprofiler_library.nix
- nix/centrosome.nix
- nix/default.nix
- nix/jgo.nix
- nix/scyjava.nix
- src/frontend/pyproject.toml
- src/subpackages/core/pyproject.toml
- src/subpackages/library/pyproject.toml
This PR adds support for building CellProfiler with the nix toolchain. It also adds a nix flake for easy distribution and composition with other flakes in the nix ecosystem.
> Feat(build): Add nix support

- cellprofiler/modules/measureimageoverlap.py
> Fix 3D display in MeasureImageOverlap

- cellprofiler/modules/measureimageskeleton.py
- tests/modules/test_measureimageskeleton.py
PR 1 of 2 (will also do in main)
> Fix measurement specification

- src/frontend/cellprofiler/modules/measureimageskeleton.py
- tests/frontend/modules/test_measureimageskeleton.py
> Fix measurement specification for MeasureImageSkeleton

- cellprofiler/modules/measureimagequality.py
PR 1 of 2, also needs to be done into main
> Fix scale selection from Image Quality measurements

- src/frontend/cellprofiler/modules/measureimagequality.py
> Fix pulling the scale value in MeasureImageQuality

- cellprofiler/modules/flagimage.py
> Fix FlagImages support for CPA3 classifiers in analysis mode

- src/subpackages/core/cellprofiler_core/modules/namesandtypes.py
> Be more careful on dtype conversion
